### ISSUE TITLE
Support count(distinct xx)

### ISSUE THREAD

**Issue by SuperManJin** [mybatis/mybatis-dynamic-sql#112]
mybatis-dynamic-sql:1.1.1
oracle jdk1.8
l want to execute the following query
`select count( distinct company_code) from table `
but `selectDistinct` function belong to `FromGatherer `
`count` function belong to `BasicColumn`
I can't construct a query through mybatis-dynamic-sql。
I am searching for a long time on net. But no use. Please help or try to give some ideas how to achieve this.
Does it support?
and What should I do if support ?
Thanks in advance.

**Comment by jeffgbutler** [comment]
This is not in the library currently, but I will add it.

In the meantime, it is very easy to add this with your own code. All you need to do is copy the existing Count class and change the render method.
