### ISSUE TITLE
Add Utility Functions to Enhance *ByExample Support

### ISSUE THREAD

**Issue by jeffgbutler** [mybatis/mybatis-dynamic-sql#118]
This is inspired by https://github.com/mybatis/generator/issues/472

Currently, the mapper interfaces generated by MyBatis Generator are a bit inconsistent. With the *ByExample methods, the user is required to code `build().render(...)` with every use. None of the other generated methods require this.

This change will introduce specialized functions that will enable a change to the code generated by MyBatis Generator. Ultimately it will allow a user to write a simpler lambda expression for a where clause. This will make client code more consistent and cleaner, and will place less burden on the user.

There will be a corresponding change in MyBatis Generator to use these new functions.

**Comment by pky920216344** [comment]
@jeffgbutler sorry (Translated by translation tools)
maybe it will increase your workload, but I really like this framework. I just found an interesting thing.
code a interface name Adapter
```
public interface Adapter<R> {
    R execute();
}
```
then let MyBatis3SelectModelAdapter、MyBatis3UpdateModelAdapter、MyBatis3DeleteModelAdapter implements  Adapter
```
public class MyBatis3UpdateModelAdapter<R> implements Adapter<R> {
}
```
```
public class MyBatis3SelectModelAdapter<R> implements Adapter<R>{
}
```
```
public class MyBatis3DeleteModelAdapter<R> implements Adapter<R>{
}
```
although it's not very useful, the code looks beautiful.
I don't know if there are any other classes that can do this.

**Comment by jeffgbutler** [comment]
Thank you for this idea. But I'm moving away from these generic adapters for updates and deletes because they force a box/unbox that isn't necessary - update and delete always return `int` with MyBatis. The new adapters are here: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/main/java/org/mybatis/dynamic/sql/util/mybatis3

I will probably deprecate and ultimately remove the old adapters after I get the generator updated to use these new capabilities.
