### ISSUE TITLE
Updating a field with a subquery value

### ISSUE THREAD

**Issue by tnicolas29200** [mybatis/mybatis-dynamic-sql#12]
Hello, it's me again

Sorry for the creation of so many issues, I'm migrating a big project to your library and suddenly I see the shortcomings of it

Is it possible to update a field of a table with a subquery ? (i don't see such a thing) :
UPDATE table SET field = (SELECT field FROM table2 WHERE id = x) WHERE id = x

**Comment by jeffgbutler** [comment]
I'm not concerned about the number of issues - I'm glad you are giving this a thorough workout!

Most of your ideas look pretty good, but it will probably take me a week or two to get to them.

**Comment by tnicolas29200** [comment]
no problem, I note in issues the concerns I encounter to write my queries with your library. 

I will try to code some if I get there to save you time.
