### ISSUE TITLE
updateByExample how to use it ?

### ISSUE THREAD

**Issue by jiatongwu** [mybatis/mybatis-dynamic-sql#120]
```java
Integer execute = hetongDynamicSqlMapper.updateByExample(null)
    .set(HetongDynamicSqlSupport.name).equalTo(hetong.getName())
    .set(HetongDynamicSqlSupport.remark).equalTo(hetong.getRemark())
    .set(HetongDynamicSqlSupport.hetongCategoryId).equalTo(hetong.getHetongCategoryId())
    .set(HetongDynamicSqlSupport.imageFilenames).equalTo(hetong.getImageFilenames())
    .where(HetongDynamicSqlSupport.id, SqlBuilder.isEqualTo(hetong.getId()))
    .build()
    .execute();

    return execute;
```

log  NullPointException 
how to use updateByExample

**Comment by jeffgbutler** [comment]
If you pass a `null` in to a method, it is expected behavior to get a NullPointerException 😃 

I'm assuming this is an updateByExample created by MyBatis Generator. In that case, use it like this:

```java
Integer execute = hetongDynamicSqlMapper.updateByExample(hetong)
    .where(HetongDynamicSqlSupport.id, SqlBuilder.isEqualTo(hetong.getId()))
    .build()
    .execute();

return execute;
```

The generated method already does all the sets.

**Comment by jiatongwu** [comment]
if hetong's property  imageFilenames is null , is it will  generate "set imageFilenames=null" sql?

**Comment by jeffgbutler** [comment]
It won't generate exactly that. It will still generate something like `set imageFileNames=?`, but will set the parameter value to null - so MyBatis will set the column value to null.

**Comment by jiatongwu** [comment]
thank you
