### ISSUE TITLE
@Results with @SelectProvider error?

### ISSUE THREAD

**Issue by jiatongwu** [mybatis/mybatis-dynamic-sql#124]
`
@Mapper
public interface ViewLogCustomMapper {
	@SelectProvider(type = SqlProviderAdapter.class, method = "select")
	List<Map<String, Object>> selectMany(SelectStatementProvider selectStatement);

	@SelectProvider(type = SqlProviderAdapter.class, method = "select")
	@Results({
			@Result(column = "id", property = "viewLog", one = @One(select = "cn.xvkang.primarymapperdynamicsql.ViewLogDynamicSqlMapper.selectByPrimaryKey")),
			@Result(column = "hetong_id", property = "hetong", one = @One(select = "cn.xvkang.primarymapperdynamicsql.HetongDynamicSqlMapper.selectByPrimaryKey")),
			@Result(column = "user_id", property = "userTable", one = @One(select = "cn.xvkang.primarymapperdynamicsql.UserTableDynamicSqlMapper.selectByPrimaryKey")),
			@Result(column = "hetong_category_id", property = "hetongCategory", one = @One(select = "cn.xvkang.primarymapperdynamicsql.HetongCategoryDynamicSqlMapper.selectByPrimaryKey")) })
	List<ViewLogAllDto> selectMany2(SelectStatementProvider selectStatement);

}
`
public class ViewLogAllDto {
	private ViewLog viewLog;
	private UserTable userTable;
	private Hetong hetong;
	private HetongCategory hetongCategory;
}

java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for cn.xvkang.primarymapperdynamicsql.HetongDynamicSqlMapper.selectByPrimaryKey

what is the namespace?
how can i do this ?

**Comment by jeffgbutler** [comment]
This was probably caused by not registering the mapper in the MyBatis configuration. Please feel free to reopen if you are still having trouble.
