### ISSUE TITLE
selectStatementProvider.getParameters() support for custom typeHandlers

### ISSUE THREAD

**Issue by krevelen** [mybatis/mybatis-dynamic-sql#131]
When I specify a custom typeHandler, in my case for mapping `org.javamoney.moneta.FastMoney` to `JdbcType.INTEGER` for a PostGreSQL database using `org.mybatis.dynamic.sql.SqlTable#column(...)`, the type handler does not seem to handle my query parameter values e.g. upon calling `SelectStatementProvider#getParameters()` as argument for the constructor of `MapSqlParameterSource(Map<>)` required by Spring's `NamedParameterJdbcTemplate#query(...)`, and I get:

    org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select ...]; nested exception is org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of org.javamoney.moneta.FastMoney. Use setObject() with an explicit Types value to specify the type to use.

**Comment by jeffgbutler** [comment]
I'm not completely following this. Do you have a small project that would be an example of the problem?

**Comment by jeffgbutler** [comment]
I've looked into this and I understand the issue now. Type handlers are a MyBatis feature and not supported by Spring.

Spring JDBC template does not have any functional equivalent to a MyBatis type handler. This is generally not a problem for mapping result sets, but it is a problem for setting prepared statement parameters. We would need to build something into the library to support something like a type handler for Spring.

I'll leave this open for now. We may add something for this in the future, but it will take some thought.

**Comment by krevelen** [comment]
Thanks, that's what I meant :-)

**Comment by jeffgbutler** [comment]
Fixed via #227
