### ISSUE TITLE
Support for update column ++

### ISSUE THREAD

**Issue by funcfoo** [mybatis/mybatis-dynamic-sql#138]
UpdateDSL.SetClauseFinisher.class:

add this method:

equalTo(plus(column,1));

**Comment by jeffgbutler** [comment]
You can do this now...

equalTo(add(column, constant("1")))

If you don't like that syntax, you could define some of your own objects/methods to create the syntax you want.

**Comment by funcfoo** [comment]
Thanks!

**Comment by funcfoo** [comment]
Thanks!
