### ISSUE TITLE
Some feedback regarding documentation

### ISSUE THREAD

**Issue by sluongng** [mybatis/mybatis-dynamic-sql#141]
I went through documentations to try picking up this library and I think there are several things can be improved:

**Major:**

- [ ] Add a reading order to the documentation.
  Documentation right now are fragmented and all over the place, as a beginner after Quick Start, i dont know which one I should be reading next.
  Perhaps a proper table of content with number ordering would be nice

- [ ] Should provide a set of completed example for each context.
  Many examples in the documentation are small snippets of a bigger program. Some variables used in these snippets are not declared within the snippets thus caused confusion until you are actually hands on with the actual code.
  I.e. https://github.com/mybatis/mybatis-dynamic-sql/blame/master/src/site/markdown/docs/mybatis3.md#L91 what is person in this snippet?

- [ ] Add documentation for testing:
  One of the reason why I prefer Mybatis over usages of other ORMs is that the query are relatively simple and can be tested separately.
  How can I test for a query generation with mybatis-dynamic-sql should be documented.

---

**Minor:**

- [ ] Generated Value: its a bit confusing given that the API of `insert()` is returning `int` as for number of rows affected by the transaction. Especially in the common case where people try to get generated primary key back after insert. Documentation should be a bit more clear that you are getting back the generated value from the POJO you used to insert, perhaps with concrete example.

**Comment by jeffgbutler** [comment]
It's a good idea to add links to complete examples.

For now, the complete Java/MyBatis example is here: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/test/java/examples/simple

If you have other ideas to improve the documentation, or contributions, they are welcome.

**Comment by sluongng** [comment]
Updated with feedback about testing documentation

**Comment by jeffgbutler** [comment]
Can you elaborate on your testing comment? Do you mean testing to verify that SQL is generated correctly? There are some tests like this in the existing code - they do not actually execute the SQL, just do checks in the generated SQL string. For example: https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/org/mybatis/dynamic/sql/select/SelectStatementTest.java

**Comment by sluongng** [comment]
> Can you elaborate on your testing comment? Do you mean testing to verify that SQL is generated correctly? There are some tests like this in the existing code - they do not actually execute the SQL, just do checks in the generated SQL string. For example: https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/org/mybatis/dynamic/sql/select/SelectStatementTest.java

Yes, the feedback is purely about documentation and testing should be documented.

Example https://docs.spring.io/spring-batch/4.1.x/reference/html/index-single.html#testing
