### ISSUE TITLE
question : how to reuse where clauses ?

### ISSUE THREAD

**Issue by cooljeffrey** [mybatis/mybatis-dynamic-sql#150]
Hello mate, thanks for this awesome lib!

I got a question trying to reuse some complex where clause between `mapper.selectMany` and `mapepr.countByExample`. With the example classes generated against runtime `MyBatis3`, I could reuse a built up example instance between `select` and `count`, how can I do this with runtime `MyBatis3DynamicSQL` ?

The purpose to reuse the where clauses is that in some situations we need to return a total count for the records matching the criteria, then do another select to return a paginated result set by setting additional offset and limit.

Looking forward to your reply, thanks!

**Comment by jeffgbutler** [comment]
This is a really interesting question! I had not considered the use case of reusing where clauses, but it makes perfect sense.

I don't have a great answer for you now, but I will look into it and see if I can make something work.

**Comment by jeffgbutler** [comment]
I've committed a potential solution in my branch here: https://github.com/jeffgbutler/mybatis-dynamic-sql/tree/reusable-where

There's a bit of noise in this for the implementation, but you can just pay attention to the test classes.

The Java test class is here: https://github.com/jeffgbutler/mybatis-dynamic-sql/blob/reusable-where/src/test/java/examples/simple/ReusableWhereTest.java

The Kotlin test class is here: https://github.com/jeffgbutler/mybatis-dynamic-sql/blob/reusable-where/src/test/kotlin/examples/kotlin/mybatis3/canonical/ReusableWhereTest.kt

Let me know what you think.

**Comment by cooljeffrey** [comment]
This looks exactly what I need.
Thanks for the quick response! I cannot wait to see this in the next release together with MBG. Cheers ~

**Comment by jeffgbutler** [comment]
Resolved via #152
