### ISSUE TITLE
how to select all in 1.1.4

### ISSUE THREAD

**Issue by maxiaoguang64** [mybatis/mybatis-dynamic-sql#156]
now i use it like this
BasicColumn[] selectList = BasicColumn.columnList(a, b, c);

**Comment by jeffgbutler** [comment]
I don't understand the question. Can you provide more details?

**Comment by maxiaoguang64** [comment]
sorry, i want to use (select * from table;)
is like this?
BasicColumn[] SELECT_LIST = BasicColumn.columnList(table.allColumns());

**Comment by jeffgbutler** [comment]
You can do that, or you can avoid creating the intermediate list this way:

select(table.allColumns())
.from(table)
...

**Comment by maxiaoguang64** [comment]
Thank you very much
