### ISSUE TITLE
JoinCondition to support plain value ?

### ISSUE THREAD

**Issue by cooljeffrey** [mybatis/mybatis-dynamic-sql#159]
The current `JoinCondition` only supports a `BasicColumn`.

    public JoinCondition(BasicColumn rightColumn) {
        this.rightColumn = rightColumn;
    }

Which makes it impossible to pass a plain value condition to the `on` operator.

    public JoinSpecificationFinisher on(BasicColumn joinColumn, JoinCondition onJoinCondition,
                JoinCriterion...andJoinCriteria) {
            return new JoinSpecificationFinisher(joinTable, joinColumn, onJoinCondition, joinType, andJoinCriteria);
        }

Sometimes we need to pass a plain value directly to the `on`: 

    leftJoin(exchange).on(travel.currency, equalTo(exchange.currencyFrom), and(exchange.currencyTo, isEqualTo("USD"))

or

    leftJoin(exchange).on(travel.currency, equalTo(exchange.currencyFrom), and("USD", isEqualTo(exchange.currencyTo))

Would it be possible to update the signature of `and` and/or `on` ?
Is there a workaround available so far ?

Thanks!

p.s the latest release is great ~

**Comment by jeffgbutler** [comment]
There are `constant` and `stringConstant` methods in the SqlBuilder that should work. So you could do this:

```
leftJoin(exchange).on(travel.currency, equalTo(exchange.currencyFrom), and(exchange.currencyTo, equalTo(stringConstant("USD")))
```

Glad you like the new release!

**Comment by cooljeffrey** [comment]
Perfect! I missed that function ...
Cheers ~
