### ISSUE TITLE
Add support of native SQL

### ISSUE THREAD

**Issue by 411937647** [mybatis/mybatis-dynamic-sql#162]
I have used mybatis-dynamic-sql in official projects,which is very convenient.I used mybatis generator to generate code.But there are two small problems.
First, the limit statement. Currently, you must call limit(pageSize).offset(index). Limit (index,pageSize) is not supported.(My database is mysql)
Second，I hope add  support of native SQL,witch can use by lambda like `table1Mapper.select(c->c.where(colunm1,isEqualTo(1)).nativeSql("and exists (select * from table2 where table1Id=1 )"))`.
The resulting SQL looks like this"select * from table1 where colunm1 =1 and exists  (select * from table2 where table1Id=1 )",or more complicated.
Now if I want to write a really complicated SQL, I can only use @selectprovider,and I have to write a new method every time.
Native SQL is important for features that are not currently supported, or for particularly complex SQL.
Would you consider add support of native SQL in next release?

**Comment by jeffgbutler** [comment]
I'm fairly certain that MySQL supports limit and offset. Have you tried it? Their documentation says they support it for compatibility with PostgreSQL: https://dev.mysql.com/doc/refman/5.7/en/select.html

I like the native SQL idea. I will  think about how best to do that.

**Comment by 411937647** [comment]
At limit problem,i mean inner class QueryExpressionWhereBuilder in class QueryExpressionDSL is lack of method,like "limie(pageIndex,pageSize)".
Generate sql like "select xxx from table limit 1,12".

**Comment by jeffgbutler** [comment]
I understand - thanks. But that is so specific to MySql that I'd rather not add it. You should be able to use the existing limit and offset support - limit(12).offset(1).

**Comment by 411937647** [comment]
Thanks a lot,my problem is solved.
Hope to see support for native SQL in the next release soon.
