### ISSUE TITLE
Is it possible to change schema on the fly?

### ISSUE THREAD

**Issue by hakan-andersson** [mybatis/mybatis-dynamic-sql#167]
I have a scenario with identical schemas and I need to be able to quickly switch between them, is this possible?

**Comment by jeffgbutler** [comment]
Yes - there is a constructor for `SqlTable` that accept a `Supplier<String>` for the schema. There is an example of using it here: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/test/java/examples/schema_supplier

**Comment by hakan-andersson** [comment]
Thank you, missed that one :)
