### ISSUE TITLE
Support for SELECT…FOR UPDATE? 

### ISSUE THREAD

**Issue by hgqapp** [mybatis/mybatis-dynamic-sql#170]
Current MyBatis Dynamic SQL version 1.1.4.

Does it support  SELECT FOR UPDATE statement to lock the records  ?

Thanks! :)

**Comment by jeffgbutler** [comment]
That is not supported currently.

**Comment by Sailfishc** [comment]
does version 1.4.0 support this feature?

**Comment by Sailfishc** [comment]
> That is not supported currently.
does version 1.4.0 support this feature?

**Comment by hellozepp** [comment]
A potentially effective way is to implement a custom SqlProviderAdapter, in the form of:
```
     @SelectProvider(type = SqlWithRecordLockProviderAdapter.class, method = "select")
     ...
     List<AclRawResource> selectMany(SelectStatementProvider selectStatement);
```

Rewrite select in SqlWithRecordLockProviderAdapter:
```
     public String select(SelectStatementProvider selectStatement) {
         return selectStatement.getSelectStatement() + " FOR UPDATE";
     }
```

This will be passed transparently when select is called:
```
MyBatis3Utils.selectList(mapper::select, selectList, acl, dsl);
```

@jeffgbutler  Please help me take a look, is this usage correct?

**Comment by jeffgbutler** [comment]
Seems like it should work - nice and simple. I like it.
