### ISSUE TITLE
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: Error instantiating class java.util.Optional with invalid types 

### ISSUE THREAD

**Issue by king-john** [mybatis/mybatis-dynamic-sql#173]
I use mybatis-spring-boot-starter + org.mybatis.dynamic-sql
call selectByPrimaryKey method throw this Exception
```
               <dependency>
			<groupId>org.mybatis.spring.boot</groupId>
			<artifactId>mybatis-spring-boot-starter</artifactId>
 			<version>2.1.1</version>
		</dependency>

		<dependency>
			<groupId>org.mybatis.dynamic-sql</groupId>
			<artifactId>mybatis-dynamic-sql</artifactId>
			<version>1.1.4</version>
		</dependency>
```

**Comment by jeffgbutler** [comment]
Please show us the code where this happens.

**Comment by king-john** [comment]
![image](https://user-images.githubusercontent.com/19261919/75503538-d5baff00-5a10-11ea-99b5-ec60393d3dc5.png)

**Comment by king-john** [comment]
```
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    default Optional<UserInfoDO> selectOne(SelectDSLCompleter completer) {
        return MyBatis3Utils.selectOne(this::selectOne, selectList, userInfoDO, completer);
    }
```

**Comment by king-john** [comment]
I use MGB with targetRuntime="MyBatis3DynamicSql"

**Comment by king-john** [comment]
Cause: java.lang.NoSuchMethodException: java.util.Optional.<init>(java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.util.Date, java.lang.Long, java.util.Date)

**Comment by king-john** [comment]
@jeffgbutler Thanks!

**Comment by jeffgbutler** [comment]
@king-john  You will need to upgrade your MyBatis version. MyBatis added support for Optional return type in 3.5.0.

(I can see in your stack trace that you are using version 3.4.6)

**Comment by king-john** [comment]
@jeffgbutler 
Thank you very much！

**Comment by chansonzhang** [comment]
> @king-john You will need to upgrade your MyBatis version. MyBatis added support for Optional return type in 3.5.0.
> 
> (I can see in your stack trace that you are using version 3.4.6)

thanks, this solved my problem
