### ISSUE TITLE
 How to combine the select part and where part independently into a DSL

### ISSUE THREAD

**Issue by liuboflyon145** [mybatis/mybatis-dynamic-sql#174]

**Comment by jeffgbutler** [comment]
I don't know what this means. Please provide an example of what you are trying to accomplish.

**Comment by liuboflyon145** [comment]
this.select(c->c.where(id, isEquals(1)))   how to change to this.count(c->c.where(id,isEquals(1)))

**Comment by jeffgbutler** [comment]
This test shows how to reuse a where clause in Java: https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/simple/ReusableWhereTest.java

This test shows the same in Kotlin:
https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/kotlin/examples/kotlin/mybatis3/canonical/ReusableWhereTest.kt
