### ISSUE TITLE
Question about complex query

### ISSUE THREAD

**Issue by bzhou003** [mybatis/mybatis-dynamic-sql#178]
Hi,

I am new to MyBatis Dynamic SQL, I have a question about the query generation here, hope someone can help. 
Here is my situation, I am using MyBatis generator to generate Model and Mapper.
This is the table:
> CREATE TABLE `payment` (
>   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
>   `user_id` bigint(20) NOT NULL,
>   `interacting_user_id` bigint(20) NOT NULL,
>   `mutual_interactions` bigint(20) NOT NULL,
>   `date_modified` timestamp NOT NULL,
>   `audience_visibility` tinyint(3) unsigned DEFAULT '0',
>   PRIMARY KEY (`id`),
>   KEY `user_payment_interactions_idx` (`user_id`,`interacting_user_id`,`mutual_interactions`,`date_modified`)
> ) ENGINE=InnoDB DEFAULT CHARSET=latin1

This is the SQL query I want to use:
`SELECT COUNT(interacting_user_id)
  FROM (
    SELECT interacting_user_id, SUM(mutual_interactions) AS interactions_per_user 
    FROM payment_interactions_biz_profile 
    WHERE user_id = $user_id
    GROUP BY interacting_user_id HAVING interactions_per_user > 1
  )
`
But I am not sure how to use SUM combined with alias in nested select. If anyone can help would be really great. Thank you.

**Comment by jeffgbutler** [comment]
Currently the library does not support nested selects or the having clause. Queries like this should be coded for MyBatis directly - which should be very easy for a query like this:

```java
@Select({
  "SELECT COUNT(interacting_user_id) FROM ( SELECT interacting_user_id, SUM(mutual_interactions) ",
  "AS interactions_per_user FROM payment_interactions_biz_profile WHERE user_id = #{value} GROUP ",
  "BY interacting_user_id HAVING interactions_per_user > 1 )"
})
int someQuery(String user_id);
```

**Comment by bzhou003** [comment]
@jeffgbutler Thank you for the information, I just tested and it works.  I will close this ticket.
