### ISSUE TITLE
What to do with functions not provided?

### ISSUE THREAD

**Issue by ContinueZhang** [mybatis/mybatis-dynamic-sql#179]
I want to use the function "string_agg", but I don't know what to do

**Comment by jeffgbutler** [comment]
We designed the library to make it relatively easy to build your own implementation of functions that are not built in. There are quite a lot of functions supplied by the library that you could use as examples. Check the code in either of the following packages:

https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/main/java/org/mybatis/dynamic/sql/select/aggregate

https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/main/java/org/mybatis/dynamic/sql/select/function

**Comment by jeffgbutler** [comment]
No response
