### ISSUE TITLE
Mapper.selectByPrimaryKey() throw ClassCastException

### ISSUE THREAD

**Issue by RisenZhong** [mybatis/mybatis-dynamic-sql#185]
![image](https://user-images.githubusercontent.com/21530821/77892499-4752cb00-72a5-11ea-9703-bf0dfc335798.png)

mybatis(mybatis-spring-boot-starter:1.3.5):3.4.6
mybatis-generator-core:1.4.0
mybatis-dynamic-sql:1.1.4

when I upgrade mybatis to 3.5.4, I got another error:
java.sql.SQLException: Conversion not supported for type java.time.LocalDateTime
![image](https://user-images.githubusercontent.com/21530821/77893555-a6fda600-72a6-11ea-9d1f-f3e669f105df.png)

**Comment by RisenZhong** [comment]
I used to use following versions, everything works fine :
mybatis(mybatis-spring-boot-starter:1.3.5):3.4.6
mybatis-generator-core:1.3.7
mybatis-dynamic-sql:1.1.2

**Comment by lany192** [comment]
I had the same problem, what happened?

**Comment by jeffgbutler** [comment]
There was a change in MyBatis version 3.5.1 in this area. MyBatis now requires a JDBC driver that implements JDBC 4.2. Make sure you've upgrade your JDBC driver. According to the following thread, it should work with connector-java 8.0.19: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/mybatis-user/NowScQE4_zc/zV7xkyOlBAAJ

It is related to the following change in MyBatis: https://github.com/mybatis/mybatis-3/pull/1478
