### ISSUE TITLE
Support UNION generation for kotlin

### ISSUE THREAD

**Issue by white-ws** [mybatis/mybatis-dynamic-sql#187]
Thank you for a great library. 

I tried to create a union query using Kotlin extension methods, but seems like `union()` method from `QueryExpressionWhereBuilder` isn't supported at the moment. Is there any workaround to do this ?

**Comment by jeffgbutler** [comment]
I'm glad you are liking MyBatis Dynamic SQL!

You are correct that union support is missing right now. I've been thinking about how to implement this - what the syntax should be. I don't have a strong feeling about that yet. I will probably post some alternatives and ask for feedback.

In the meantime, if you have a suggestion as to what the syntax should be I would love to see it.
