### ISSUE TITLE
Support LAST_INSERT_ID

### ISSUE THREAD

**Issue by tytannial** [mybatis/mybatis-dynamic-sql#188]
Could I get the last insert id by auto_increment from insert result?

**Comment by jeffgbutler** [comment]
Yes - this is supported by MyBatis natively and this library as well. There is a working example here: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/test/java/examples/generated/always/mybatis

Look for the insert method in the mapper - it has an annotation like this:
```java
@Options(useGeneratedKeys=true, keyProperty="record.fullName")
```

Also see the MyBatis FAQ here: https://github.com/mybatis/mybatis-3/wiki/FAQ#how-can-i-retrieve-the-value-of-an-auto-generated-key

**Comment by tytannial** [comment]
Oh, useGeneratedKeys can be used.  Thanks! 👍
