### ISSUE TITLE
How to self connect query?

### ISSUE THREAD

**Issue by ContinueZhang** [mybatis/mybatis-dynamic-sql#193]
How to self connect query?

**Comment by jeffgbutler** [comment]
There is an example of self joins in the tests here: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/test/java/examples/joins

Basically you make a copy of the SqlTable and columns, then use it like any other table.

**Comment by carzyhub** [comment]
How do I use self Join in Kotlin?
