### ISSUE TITLE
How can I build a sql as 'select xxx for update'

### ISSUE THREAD

**Issue by zhyusgethup** [mybatis/mybatis-dynamic-sql#194]
How can I build a sql as 'select xxx for update'

**Comment by jeffgbutler** [comment]
The library doesn't support this currently, but you could implement it yourself using a custom model. There's an example of doing something similar here: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/test/java/examples/paging

I'd like to make this easier in the future, but for now this is the best way.

**Comment by zhyusgethup** [comment]
thanks for yours help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jeff Butler"<notifications@github.com&gt;; 
发送时间: 2020年4月27日(星期一) 凌晨5:37
收件人: "mybatis/mybatis-dynamic-sql"<mybatis-dynamic-sql@noreply.github.com&gt;; 
抄送: "多又多"<2649160284@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mybatis/mybatis-dynamic-sql] How can I build a sql as &#39;select xxx for update&#39; (#194)





 
The library doesn't support this currently, but you could implement it yourself using a custom model. There's an example of doing something similar here: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/test/java/examples/paging
 
I'd like to make this easier in the future, but for now this is the best way.
