### ISSUE TITLE
Use 'join' sometimes failed

### ISSUE THREAD

**Issue by zhyusgethup** [mybatis/mybatis-dynamic-sql#199]
Thank you for your time. sir.
I use 'left join' for 5 tables which have some columns of the same name. When every table has  datas, it works ok! But if some tables don't have datas, it works wrong. The other talbe's java models will be not null, and it's field of the same name as the first tables will have it's value!
I guess that columns alias can correct it, but I don't want to write every columns in java.

**Comment by jeffgbutler** [comment]
Using aliases for duplicate column names is the only reliable way to handle this. Some databases can use a combination of tableName.columnName to distinguish between duplicate column names, but this is not universal. You might try altering your result maps to see if it will work in your case.

**Comment by zhyusgethup** [comment]
Thank you, Sir. I wil try.
