### ISSUE TITLE
Make the "column" function of SqlColumn static

### ISSUE THREAD

**Issue by tnicolas29200** [mybatis/mybatis-dynamic-sql#2]
Hello,

It'll be great if the column function of the SqlColumn class was static : 

Personnaly, i prefer duplicate the "table" parameter on each call of column :
`public static final SqlTable table = new SqlTable("table');
public final SqlColumn<Integer> id = SqlTable.column(table , "id", JDBCType.INTEGER);
        public final SqlColumn<String> firstName = SqlTable.column(table , "first_name", JDBCType.VARCHAR);
        public final SqlColumn<String> lastName = SqlTable.column(table , "last_name", JDBCType.VARCHAR);
        public final SqlColumn<Date> birthDate = SqlTable.column(table , "birth_date", JDBCType.DATE);
        public final SqlColumn<Boolean> employed = SqlTable.column(table , "employed", JDBCType.VARCHAR, "examples.simple.YesNoTypeHandler");
        public final SqlColumn<String> occupation = SqlTable.column(table , "occupation", JDBCType.VARCHAR);
`

rather than dupliate all the field because the column function need "this" on the code for getting the table object : 
`public static final SimpleTable simpleTable = new SimpleTable();
    public static final SqlColumn<Integer> id = simpleTable.id;
    public static final SqlColumn<String> firstName = simpleTable.firstName;
    public static final SqlColumn<String> lastName = simpleTable.lastName;
    public static final SqlColumn<Date> birthDate = simpleTable.birthDate;
    public static final SqlColumn<Boolean> employed = simpleTable.employed;
    public static final SqlColumn<String> occupation = simpleTable.occupation;
    
    public static final class SimpleTable extends SqlTable {
        public final SqlColumn<Integer> id = column("id", JDBCType.INTEGER);
        public final SqlColumn<String> firstName = column("first_name", JDBCType.VARCHAR);
        public final SqlColumn<String> lastName = column("last_name", JDBCType.VARCHAR);
        public final SqlColumn<Date> birthDate = column("birth_date", JDBCType.DATE);
        public final SqlColumn<Boolean> employed = column("employed", JDBCType.VARCHAR, "examples.simple.YesNoTypeHandler");
        public final SqlColumn<String> occupation = column("occupation", JDBCType.VARCHAR);

        public SimpleTable() {
            super("SimpleTable");
        }
    }`

**Comment by jeffgbutler** [comment]
I don't think you need a new static method in SqlTable - you could just use the Builder in SqlColumn directly like this:

```java
public static final SqlTable table = new SqlTable("table');
public final SqlColumn<Integer> id = SqlTable.withName("id")
    .withTable(table)
    .withJdbcType(JDBCType.INTEGER)
    .build();
```

Would that work for you?

**Comment by tnicolas29200** [comment]
Hello,

Thank you for your response.

You're right, i can use the builder directly, but it's more complex then calling a static function with 3 arguments. Perhaps you could write 2 methods : a static one and a "normal" one to facilitate the use of your library.
In fact, i have done this comportement with an overriding of the SqlTable in my own code but i imagine that i'm not the only one to think that it'll be a good idea to have a shortcut for that.
