### ISSUE TITLE
How to use batch insert or batch update?

### ISSUE THREAD

**Issue by 411937647** [mybatis/mybatis-dynamic-sql#204]
At present, there are batch inserts in my project, usually more than thousands of them. 
The single insert method generated by mybatis generator has seriously slowed down the performance.
How to use batch insert or batch update in mybatis-dynamic-sql?

**Comment by jeffgbutler** [comment]
Here's information about how batches work in MyBatis: https://github.com/mybatis/mybatis-3/wiki/FAQ#how-do-i-code-a-batch-insert

You can use MyBatis batch support directly with this library.

This library has two other extensions for batch:

1. There is support with the insert statement to translate a list of records to a stream of insert statements for MyBatis batch. You can read about that here: https://mybatis.org/mybatis-dynamic-sql/docs/insert.html
1. There is also support for Spring Batch if you want to use that. You can read about Spring Batch support here: https://mybatis.org/mybatis-dynamic-sql/docs/springBatch.html

**Comment by jeffgbutler** [comment]
Closing as no further comments. Feel free to ask questions on the mailing list or on StackOverflow.
