### ISSUE TITLE
How can set/where Bitwise Operators

### ISSUE THREAD

**Issue by LH-gulongfei** [mybatis/mybatis-dynamic-sql#213]
I want 
update table set tag = tag | 2 where tag & 2 = 2

**Comment by andruet** [comment]
Have you found a solution? I encountered the same problem.

**Comment by jeffgbutler** [comment]
You should be able to code your own functions for bitwise operators. You can use the included functions as examples: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/main/java/org/mybatis/dynamic/sql/select/function

**Comment by andruet** [comment]
Why not directly support these common operations? Or a simple construction method for these common operations.

**Comment by LH-gulongfei** [comment]
> Have you found a solution? I encountered the same problem.

public SqlColumn<Integer> bitEquleTo(SqlColumn column, int bit){
 return SqlTable.of("dynamic").column(String.format("%s & %s"),column.name(), bit),JDBCType,INTEGER);
}

demo:
// select * from table where flag & 4 = 4
mapper.select(x -> x.where(bitEqualTo(flag, 4), isEqualTo(4))
