### ISSUE TITLE
when i use isIn(emptyList) where condition, it would not render to sql

### ISSUE THREAD

**Issue by clcy1243** [mybatis/mybatis-dynamic-sql#228]
code example
```
select(s -> s.where(id, isIn(new ArrayList<>()));
```
will render like this
```
select * from table
```
it should be  like 
```
select * from table where id in ()
```
and mysql where throw exception when execute this sql, it's what my want,
so i think there is a bug,
i found this code at `org.mybatis.dynamic.sql.where.render.WhereConditionVisitor<T>`
```
    public Optional<FragmentAndParameters> visit(AbstractListValueCondition<T> condition) {
        FragmentCollector fc = (FragmentCollector)condition.mapValues(this::toFragmentAndParameters).collect(FragmentCollector.collect());
        return fc.isEmpty() ? Optional.empty() : FragmentAndParameters.withFragment(condition.renderCondition(this.columnName(), fc.fragments())).withParameters(fc.parameters()).buildOptional();
    }
```
if list value condition accept an empty list, fc.isEmpty() will be true, this condition where be deleted

could anyone fix this?

**Comment by jeffgbutler** [comment]
I don't agree this is a bug - I think it is actually a good thing that the library won't generate invalid SQL. I think it would be best to check to see if the list is empty before trying to execute the statement. If it is a possibility in your app that the list could be empty, then do you really want to rely on causing a database exception as a kind of validation?

Honestly it wouldn't be too hard to provide an option to render these conditions even when they are empty. But I'm not convinced that is a good idea.

Thoughts???

**Comment by clcy1243** [comment]
> I don't agree this is a bug - I think it is actually a good thing that the library won't generate invalid SQL. I think it would be best to check to see if the list is empty before trying to execute the statement. If it is a possibility in your app that the list could be empty, then do you really want to rely on causing a database exception as a kind of validation?
> 
> Honestly it wouldn't be too hard to provide an option to render these conditions even when they are empty. But I'm not convinced that is a good idea.
> 
> Thoughts???

if i want ignore invalid condition, i will use `IsInWhenPresent` but not `IsIn`, i think there is `IsInWhenPresent` method, so `IsIn` mean it will render this condition even if it is invalid

**Comment by clcy1243** [comment]
there is two method do same thing with diff name

**Comment by jeffgbutler** [comment]
`IsInWhenPresent` filters null values out of the list. It will still not render if the list ends up being empty.

**Comment by clcy1243** [comment]
with 1.3.7 generator, i use Example, when i use `andIdIn(emptyList)`, will throw exception,

**Comment by clcy1243** [comment]
there is a problem, when i build sql with not valid param, it where change more data than what i want it modify, 
and i should check param each step now

**Comment by jeffgbutler** [comment]
I get it. I really do think you should be validating, but I understand it could be a change to how you're working now and not doing it would cause undesirable side effects.

I've been experimenting a bit. I can enable you to write a condition that will force the exception with a very simple code change. I'll push something to address this shortly.

**Comment by clcy1243** [comment]
Thanks for understanding

**Comment by clcy1243** [comment]
Here is 4:00am, I will try it when I waked up.

**Comment by jeffgbutler** [comment]
See documentation here: https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/site/markdown/docs/conditions.md#optionality-with-the-in-conditions

I will release the new version in the next few days.

**Comment by clcy1243** [comment]
i code like this 
```

    public static <T> IsIn<T> isInRequired(Collection<T> values) {
        if (CollectionUtils.isEmpty(values)) {
            throw new ZhqcException(WmsResponseEnum.CUSTOMIZE_MSG, "param could not be empty at where in condition");
        }
        return IsIn.of(values);
    }
```
to fix my codes now.

ur idea is so good, I don't try to expland where codition before,
I think i can use `mybatis-dynamic-sql` do more amazing things than before.

**Comment by jeffgbutler** [comment]
@clcy1243 I like your solution a lot! This is much better than forcing the library to generate invalid SQL. I'm going to remove the change I made and use your example in the docs.

**Comment by jesusslim** [comment]
I don't think `isInRequired` or `withListEmptyCallback` is a good solution.Because if we can remember to use `isInRequired`,of course we can also remember to check empty list before `isIn`.
I can understand that you never want to build invalid sql, but in my opinion, once we use `isIn`, whatever param we pass, you should never change our sql, if you think our sql is invalid just throw exception, not change it to another wrong sql.
if we pass empty list, the sql should be `in ()`,you can't change it to query full table, because it will be a disaster in production if we have a table with big data. And if we use it in `delete`, it will delete all rows, it's a real disaster because you changed our sql wrong for "valid sql".
And also every time in code review, we have to take time to check if we checked empty list or not before `isIn`.
It will be a good solution if there is a config setting to decision throw exception or query full table when isIn empty list.

**Comment by zhenchuan9r** [comment]
I would like to view this as a bug.
It is very contradicting normal understanding of the declaration of the where clause.
It is at least a very unfriendly design.
But thanks for changing the design to a normal track.

**Comment by jeffgbutler** [comment]
@zhenchuan9r If you have found a bug, please open a new issue. It is ineffective to comment on an issue that has been closed for three years.

**Comment by zhenchuan9r** [comment]
> @zhenchuan9r If you have found a bug, please open a new issue. It is ineffective to comment on an issue that has been closed for three years.

I encountered the same problem as this issue.
As this issue has already been resolved, it is not necessary for me to open a new issue.
