### ISSUE TITLE
In the same transaction, a specific piece of data is queried and modified but not persisted. Will the modified but not persisted data be found after querying the piece of data?

### ISSUE THREAD

**Issue by ContinueZhang** [mybatis/mybatis-dynamic-sql#236]
In the same transaction, a specific piece of data is queried and modified but not persisted. Will the modified but not persisted data be found after querying the piece of data?

**Comment by jeffgbutler** [comment]
I think this question is not related to this library. This library is an SQL DSL - it does not execute SQL.

If you are asking about MyBatis, then the answer really depends on how you configure caching in your application. MyBatis will cache result sets, but this is a lower level abstraction than an ORM like Hibernate where changes to objects can be transparently persisted back to the database.

I suggest you ask further questions about this on the MyBatis user list, or StackOverflow.
