### ISSUE TITLE
insertMultiple unsupport oracle batch insert

### ISSUE THREAD

**Issue by topsoft-support** [mybatis/mybatis-dynamic-sql#242]
`org.mybatis.dynamic.sql.insert.render.FieldAndValueCollector#multiRowInsertValuesPhrase`

`org.mybatis.dynamic.sql.insert.render.MultiRowInsertRenderer#calculateInsertStatement`

`org.mybatis.dynamic.sql.insert.render.MultiRowInsertRenderer#render`

use `insertMultiple` the `insertStatement` is like `insert into table_name (xx,xx) values (?,?),(?,?)` ,oracle doesn't support it.

any plan?

**Comment by topsoft-support** [comment]
dynamic sql is not fully dynamic implementation

**Comment by jeffgbutler** [comment]
Oh Oracle...

I don't plan on adding something specific for Oracle. As far as I know, Oracle does support JDBC batch operations so you should be able to use the batch support in this library. For Oracle's odd multi-row insert syntax, you can write those those statements directly in MyBatis or Spring.

**Comment by topsoft-support** [comment]
> Oh Oracle...
> 
> I don't plan on adding something specific for Oracle. As far as I know, Oracle does support JDBC batch operations so you should be able to use the batch support in this library. For Oracle's odd multi-row insert syntax, you can write those those statements directly in MyBatis or Spring.

Yeah，At present, I write those statements in mybatis.
