### ISSUE TITLE
Support for Postgresql Array query ?

### ISSUE THREAD

**Issue by redwolf2019** [mybatis/mybatis-dynamic-sql#257]
- Postgresql support data type of array:https://www.postgresql.org/docs/9.1/arrays.html
  -  native query like ``` select * from user where 1 = any (1,2,3)```
- is it possable `mybatis-dynamic-sql(without XML)` support this?

**Comment by jeffgbutler** [comment]
This library supports Arrays like any other data type. The real challenge with Arrays is in the underlying execution engine.

I'm assuming you want to use MyBatis for executing SQL. If you're using Spring JDBC template than the concepts are similar.

I've committed a complete example for working with Arrays in MyBatis here: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/test/java/examples/array

The key is to get the type handler working correctly. MyBatis has a built-in type handler for Arrays, but it is somewhat limited in function - it will only handle arrays that are declared as `Object`.  My example shows how to build a type handler that will return String arrays.

Another limitation of the MyBatis Array type handler is that it only handles single dimensional arrays. PostgreSQL supports multi-dimensional arrays. If you want to use multi-dimensional arrays, then you will need to write your own type handler.

**Comment by jeffgbutler** [comment]
No response.

**Comment by uywojh** [comment]
maybe like this:
public class ImmutablePairIsAnyForString extends AbstractSingleValueCondition<String[]> {

    private ImmutablePairIsAnyForString(String[] value) {
        super(value);
    }

    @Override
    public ImmutablePairIsAnyForString filter(Predicate<? super String[]> predicate) {
        return  filterSupport(predicate, ImmutablePairIsAnyForString::empty, (ImmutablePairIsAnyForString) this);
    }

    @Override
    public String renderCondition(String columnName, String placeholder) {
        StringBuilder sb = new StringBuilder();
        sb.append("'").append(value[0]).append("'").append(" = ").append(" any(coalesce(").append(columnName).append(", array[]::VARCHAR[]))");
        return sb.toString();
    }

    public static ImmutablePairIsAnyForString of(String[] value) {
        return new ImmutablePairIsAnyForString(value);
    }

    private static ImmutablePairIsAnyForString empty() {
        return EMPTY;
    }

    private static final ImmutablePairIsAnyForString EMPTY = new ImmutablePairIsAnyForString((String[]) null) {
        @Override
        public boolean shouldRender() {
            return false;
        }
    };
}

Integer[] typeArr = {OrganizationTypeEnum.HOSPITAL.getType()};
ImmutablePairIsAny typeAny = ImmutablePairIsAny.of(typeArr).filter(ArrayUtils::isNotEmpty);

SqlBuilder.or(HealthArticleDynamicSqlSupport.matchesChannelTypes, typeAny)
