### ISSUE TITLE
Map underscore to camel case for SqlColumn objects

### ISSUE THREAD

**Issue by a188037445** [mybatis/mybatis-dynamic-sql#272]
When I query data with `CommonSelectMapper.selectManyMappedRows()` method, it can't map underscore to camel case automatically, I have to specify an alias for every cloumn, I think we can do something to improve this.

The way I can think of is to add a method like `asCamelCase` for `SqlColumn` class, which can convert the name of the column to camel case, and return a new `SqlColumn` object, what do you think?

**Comment by jeffgbutler** [comment]
Thanks - I think this is a good idea. I'm doing some experimentation with it, then will commit something.
