### ISSUE TITLE
Support for nested select query

### ISSUE THREAD

**Issue by TMakaku** [mybatis/mybatis-dynamic-sql#297]
I would like be able to add a subquery to my SelectModel (using MyBatis Dynamic SQL), see the the following example:

```
SELECT name,
  (COUNT id from foo_child)
 FROM foo
WHERE ..
```
I tried to combine 2 selectmodels or to create my own custom model but this doesn't seem possible.

The only way i've gotten it to work is the use the resulting sql string, manipulate it, then make a new SelectStatementProvider... But that defeats the purpose of using dynamic SQL

**Comment by jeffgbutler** [comment]
I'll think about this - it might not be quick or elegant to implement.

But I think that most of these type of queries can be rewritten as joins - and will likely perform better that way too.

For example this is similar to what you have above...

```sql
select im.item_id, count(ol.order_id) as numberOfOrders
from ItemMaster im left join OrderLine ol on im.item_id = ol.item_id
group by item_id
order by item_id
```

These types of join queries are supported today by the library.

**Comment by TMakaku** [comment]
My example is incomplete.
I am using a join comparable to your example, but the problem still remains that i cannot use the count in this manner.
Or am i mistaken?

Is it possible to combine a count and 'normal' select of BasicColumns?

**Comment by jeffgbutler** [comment]
Please post an example of the SQL you are trying to generate. It's hard to help with nothing to go on. But yes, you can combine count and BasicColumn. Here is an example of a similar query:

```java
SelectStatementProvider selectStatement = select(itemMaster.itemId,
            count(orderLine.orderId).as("numberOfOrders"))
        .from(itemMaster, "im").leftJoin(orderLine, "ol")
        .on(itemMaster.itemId, equalTo(orderLine.itemId))
        .groupBy(itemMaster.itemId)
        .orderBy(itemMaster.itemId)
        .build()
        .render(RenderingStrategies.MYBATIS3);
```

**Comment by TMakaku** [comment]
Ah! the mistake i made was using a collection of BasicColumn instead of BindableColumn.
I missed the fact that Count conformed to the BindableColumn interface.

I should be able to rewrite my ugly workaround.

Thanks for your swift replies!

**Comment by jeffgbutler** [comment]
BindableColumn extends BasicColumn so you can mix and match in a select list.
