### ISSUE TITLE
Only offset error for mariadb

### ISSUE THREAD

**Issue by darkgirl** [mybatis/mybatis-dynamic-sql#311]
version info
`
implementation 'org.mybatis.dynamic-sql:mybatis-dynamic-sql:1.2.1'
mariadb 10.3.9
`
my code
`
			SelectStatementProvider selectStatement = select(proxyInformation.allColumns())
					.from(proxyInformation)
//					.limit(1)
					.offset(1)
					.build()
					.render(RenderingStrategies.MYBATIS3);

			List<ProxyInformation> rows = mapper.selectMany(selectStatement);
`
debug info:
`
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax;
`

**Comment by jeffgbutler** [comment]
Perhaps this should be a bug report for MariaDB? The library is generating SQL as expected and other databases support this syntax. We have a passing test for this here: https://github.com/mybatis/mybatis-dynamic-sql/blob/3b7a35734a4689257555f60a2e1a977ab4117c4f/src/test/java/examples/animal/data/LimitAndOffsetTest.java#L110-L129

For now it looks like you will need to provide both limit and offset with MariaDB.

**Comment by darkgirl** [comment]
> Perhaps this should be a bug report for MariaDB? The library is generating SQL as expected and other databases support this syntax. We have a passing test for this here:
> 
> https://github.com/mybatis/mybatis-dynamic-sql/blob/3b7a35734a4689257555f60a2e1a977ab4117c4f/src/test/java/examples/animal/data/LimitAndOffsetTest.java#L110-L129
> 
> For now it looks like you will need to provide both limit and offset with MariaDB.

thanks
