### ISSUE TITLE
[Question] is there any way to print explain information?

### ISSUE THREAD

**Issue by darkgirl** [mybatis/mybatis-dynamic-sql#312]
Hi
as you can know, if we use mybatis, it is not easy to get fully sql because of perpare statement, all variant become '?'
so is there any way to print explain information? 
such as, provide a function  explainSelect to print explain info for `explain select * from tablename`

and another question is,
to use dynamic sql, is there anything need to notice for prevent sql inject?

thanks.

**Comment by jeffgbutler** [comment]
Please use the mailing list or stackoverflow for questions.

You probably don't want to use MyBatis to run `explain plan` statements - those are usually run interactively by a DBA. If you enable logging in MyBatis, you will see the statements (with the `?`) in the logs. You can pull the statements out of the logs for running explain plan.

SQL injection is mostly avoided by using prepared statements - and this library uses prepared statements exclusively. There are some potential vulnerabilities when using the `constant(String)`, or `sortColumn(String)` methods - so be careful if you use them.
