### ISSUE TITLE
How to support functions/expression in condition？

### ISSUE THREAD

**Issue by BreatherLeiYu** [mybatis/mybatis-dynamic-sql#313]
I want to render a sql like select * from t_order where create_at > date_sub(current_date,interval 1 day)
But up to now it will be render like select * from t_order where create_at > 'date_sub(current_date,interval 1 day)'
I have to refactor WhereConditionVisitor.visit with FragmentAndParameters

**Comment by BreatherLeiYu** [comment]
I thought it could refer to jooq dsl.conditon to handle this

**Comment by jeffgbutler** [comment]
You can use `org.mybatis.dynamic.sql.Constant` - this will not render the quotes.

If you don't want to use a constant, or if you want to build a "date_sub" function that accepts different parameters, you can write a class that implements BindableColumn - there are quite a few examples of doing this with the built in functions.

**Comment by BreatherLeiYu** [comment]
> 
> 
> You can use `org.mybatis.dynamic.sql.Constant` - this will not render the quotes.
> 
> If you don't want to use a constant, or if you want to build a "date_sub" function that accepts different parameters, you can write a class that implements BindableColumn - there are quite a few examples of doing this with the built in functions.
lgtm
thx a lot

**Comment by smycv** [comment]
dear god 
Why not an example (or link) here？I need achieve where style = CAST("{\"fill\":\"#00C691\"}" as JSON)

**Comment by smycv** [comment]
@jeffgbutler

**Comment by jeffgbutler** [comment]
https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/main/java/org/mybatis/dynamic/sql/select/function/Cast.java
