### ISSUE TITLE
issue about dynamic code generator performance

### ISSUE THREAD

**Issue by monical1** [mybatis/mybatis-dynamic-sql#322]
Any attempts to test at high concurrents? I would like to know more about the sql execute performance between mybatis(xml/annotation), since there is no any descriptive documents found, thanks in advance~

**Comment by jeffgbutler** [comment]
None that I know of. My assumption is that any benefit or lag in performance for using this library is very small compared to the performance of the underlying execution framework (MyBatis or Spring) and the database itself.

That said it makes sense to me that very dynamic queries generated by this library would perform better that trying to replicate the same function in XML or one of the other interpreted scripting languages. But I have not tested that assumption.
