### ISSUE TITLE
Level 2 Cache maintenance

### ISSUE THREAD

**Issue by alexey-su** [mybatis/mybatis-dynamic-sql#324]
I want to use the cache of the 2nd level.
Add annotations.

	@CacheNamespace
	public interface FieldsMapper {

	    @SelectProvider(type = SqlProviderAdapter.class, method = "select")
		ist<MyObject> selectMany(SelectStatementProvider selectStatement);

	    @Options(flushCache = FlushCachePolicy.TRUE)
	    default int delete(DeleteDSLCompleter completer) {
	        return MyBatis3Utils.deleteFrom(this::delete, fieldsTable, completer);
	    }	

	    @Options(flushCache = FlushCachePolicy.TRUE)
	    default int update(UpdateDSLCompleter completer) {
	        return MyBatis3Utils.update(this::update, fieldsTable, completer);
	    }
	}

* The system itself recognizes the cache cleanup as @Update, @Delete.
* You need to put the @Options annotation.
* @Options will work on "default method".

What is the model of behavior with the cache?

**Comment by jeffgbutler** [comment]
I'm not sure what you are asking.

If you are asking about the *@options* annotation, that is part of the base MyBatis project, not this project.

Can you elaborate on your question?

**Comment by alexey-su** [comment]
Accidentally discovered a problem. In one transaction, we read the data and send it to the web browser. In the second transaction, it updates the data. If you read the data, it will be old.
If I remove the use of the CacheNamespace annotation, the error disappears.


	public interface FieldsMapper extends  CommonCountMapper, CommonDeleteMapper, CommonInsertMapper<MyObject>, CommonUpdateMapper {
		...
	}


I think there is a problem with the annotation analysis in the underlying interfaces. For example

	public interface CommonUpdateMapper {
    	@UpdateProvider(type = SqlProviderAdapter.class, method = "update")
    	int update(UpdateStatementProvider updateStatement);
	}

**Comment by jeffgbutler** [comment]
Ah - I understand. I'll take a look at this.

**Comment by jeffgbutler** [comment]
I've written some tests with a variety of commit and rollback configurations and everything is working as I think it should. Take a look here: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/test/java/issues/gh324

If this doesn't help, please create a test similar to this that demonstrates the issue you are facing.

**Comment by jeffgbutler** [comment]
Closing as I don't think there is an issue here. Feel free to reopen if you discover a reproducible failure.
