### ISSUE TITLE
Self Join - inquires

### ISSUE THREAD

**Issue by znh0503** [mybatis/mybatis-dynamic-sql#340]
if sql
```sql
SELECT *
FROM gms_goods_category ggc1 INNER JOIN gms_goods_category ggc2
   ON ggc1.id=ggc2.parent_id WHERE ggc2.id=19
```

java
```java
SelectStatementProvider selectStatement = SqlBuilder.select(GmsGoodsCategoryMapper.selectList)
                .from(GmsGoodsCategoryDynamicSqlSupport.gmsGoodsCategory,"ggc1")
                .join(GmsGoodsCategoryDynamicSqlSupport.gmsGoodsCategory,"ggc2")
                .on(????????????????????????????????????????)
                .build().render(RenderingStrategy.MYBATIS3);
```

How to write in the on()

**Comment by jeffgbutler** [comment]
This will be somewhat easier in the next release. For now, you can do it like this:

```java
GmsGoodsCategoryDynamicSqlSupport.GmsGoodsCategory gmsGoodsCategory2 =
   new GmsGoodsCategoryDynamicSqlSupport.GmsGoodsCategory();

SelectStatementProvider selectStatement = SqlBuilder.select(GmsGoodsCategoryMapper.selectList)
                .from(GmsGoodsCategoryDynamicSqlSupport.gmsGoodsCategory,"ggc1")
                .join(gmsGoodsCategory2,"ggc2")
                .on(GmsGoodsCategoryDynamicSqlSupport.gmsGoodsCategory.id, equalTo(gmsGoodsCategory2.parent_id))
                .where(gmsGoodsCategory2.id, isEqualTo(19))
                .build()
                .render(RenderingStrategy.MYBATIS3);
```

There's an example in the tests here: https://github.com/mybatis/mybatis-dynamic-sql/blob/409019838ac599a543b2bfdedd78f4e0386a8ee6/src/test/java/examples/joins/JoinMapperTest.java#L916-L945

**Comment by znh0503** [comment]
> This will be somewhat easier in the next release. For now, you can do it like this:
> 
> ```java
> GmsGoodsCategoryDynamicSqlSupport.GmsGoodsCategory gmsGoodsCategory2 =
>    new GmsGoodsCategoryDynamicSqlSupport.GmsGoodsCategory();
> 
> SelectStatementProvider selectStatement = SqlBuilder.select(GmsGoodsCategoryMapper.selectList)
>                 .from(GmsGoodsCategoryDynamicSqlSupport.gmsGoodsCategory,"ggc1")
>                 .join(gmsGoodsCategory2,"ggc2")
>                 .on(GmsGoodsCategoryDynamicSqlSupport.gmsGoodsCategory.id, equalTo(gmsGoodsCategory2.parent_id))
>                 .where(gmsGoodsCategory2.id, isEqualTo(19))
>                 .build()
>                 .render(RenderingStrategy.MYBATIS3);
> ```
> 
> There's an example in the tests here:
> 
> https://github.com/mybatis/mybatis-dynamic-sql/blob/409019838ac599a543b2bfdedd78f4e0386a8ee6/src/test/java/examples/joins/JoinMapperTest.java#L916-L945

So it can run,thanks!!!Looking forward to the next release.
