### ISSUE TITLE
Compatibility between mybatis, mybatis generator and mybatis dynamic sql?

### ISSUE THREAD

**Issue by wlnirvana** [mybatis/mybatis-dynamic-sql#347]
When using the MyBatis3DynamicSql runtime of MyBatis generator, the generated source depends on mybatis-dynamic-sql (and mybatis as well of course) by default. But there does not seem to be any official documentation on the compatibility of these packages. Any pointers?

**Comment by jeffgbutler** [comment]
Are you looking for information about versions? We usually put that kind of information in the release notes/change log. For example, here's the change log for the generator: https://mybatis.org/generator/whatsNew.html. It states that the MyBatis3DynamicSql runtime in version 1.4.0 of MyBatis generator depends on version 1.1.3 or later of MyBatis Dynamic SQL.
