### ISSUE TITLE
Difference between RenderingStrategies

### ISSUE THREAD

**Issue by wlnirvana** [mybatis/mybatis-dynamic-sql#348]
There are currently two RenderingStrategies, namely `MYBATIS3` and `SPRING_NAMED_PARAMETER`. What are the differences between them? How/when should they be used?

**Comment by jeffgbutler** [comment]
The library renders SQL and parameters for use both by MyBatis3 and by Spring's Named Parameter JDBC template. I think of those two things as "SQL execution engines". The library includes utilities to make it easy to use the generated SQL with either of those engines.

You should use the rendering strategy that matches the SQL execution engine you are using. There are lots of examples of using the library with both underlying tools. You can see pointers to the different example here: https://github.com/mybatis/mybatis-dynamic-sql
