### ISSUE TITLE
Dynamic select with zero to many filter criteria

### ISSUE THREAD

**Issue by grambbledook** [mybatis/mybatis-dynamic-sql#37]
Hi guys, I'm curious how I can dynamically  define query with zero to dozen filter criteria in where clause using query dsl.

Right now i'm using `where(id, isNotNull())` first and then adding `and` and `or` conditions for every column in filter criteria. Is there any other ways to do it?

**Comment by jeffgbutler** [comment]
I'm working on something that, I think, will help.  I assume you're doing something like this:

```java
QueryExpressionDSL<SelectModel>.QueryExpressionWhereBuilder qdl = select(id, firstName, lastName)
        .from(person)
        .where(id, isNotNull());
        
if (fn != null) {
    qdl.and(firstName, isEqualTo(fn));
}
        
if (ln != null) {
    qdl.or(lastName, isNotEqualTo(ln));
}
        
SelectStatementProvider selectStatement = qdl
        .build()
        .render(RenderingStrategy.MYBATIS3);
```
That's kind of ugly and unwieldy and it has the unnecessary first condition. What I'm working on looks more like this:

```java
SelectStatementProvider selectStatement = select(id, firstName, lastName)
        .from(person)
        .where(firstName, isEqualToIfPresent(fn))
        .or(lastName, isNotEqualToIfPresent(ln))
        .build().render(RenderingStrategy.MYBATIS3);
```
Couple of questions for you...

1. Do I understand your need correctly?
2. What do you think of this syntax and do you have any suggestions?

**Comment by grambbledook** [comment]
Yeah, mine approach is a bit ugly and it would be awesome to have  some kind of optional conditions which are skipped at render stage.

**Comment by jeffgbutler** [comment]
This support is now in the master branch and the snapshot version.  I will cut a release soon.  I changed the syntax to "xxxwhenPresent":

```java
SelectStatementProvider selectStatement = select(id, firstName, lastName)
        .from(person)
        .where(firstName, isEqualToWhenPresent(fn))
        .or(lastName, isNotEqualToWhenPresent(ln))
        .build()
        .render(RenderingStrategy.MYBATIS3);
```
