### ISSUE TITLE
Is there any why to dynamically apply a where condition without using WhereClauseProvider?

### ISSUE THREAD

**Issue by mobileharry** [mybatis/mybatis-dynamic-sql#381]
Is there any why to dynamically apply a where condition without using WhereClauseProvider? Something like: 

WhereDSL wdsl = new WhereDSL();
wdsl.where(userId, isEqualTo(1));

SelectStatementProvider sql = select(table1.allColumns())
                .from(table1)
				.applyWhere(wdsl)
				.build().render(RenderingStrategies.MYBATIS3);

In my scenario, I need to make the WHERE condition as a parameter in the function. I really don’t want to hard-code the SELECT statement and use WhereClauseProvider in either annotation or XML which is like the “Stand Alone Where Clauses” example, because I want to make my code more flexible.

**Comment by jeffgbutler** [comment]
This can be accomplished with a `WhereApplier`. There is a full example here: https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/simple/ReusableWhereTest.java

The code looks like this:

```java
WhereApplier commonWhere = d -> d.where(userId, isEqualTo(1));

SelectStatementProvider sql = select(table1.allColumns())
    .from(table1)
    .applyWhere(commonWhere)
    .build()
    .render(RenderingStrategies.MYBATIS3);
```

**Comment by mobileharry** [comment]
Hi Jeff,

Thank you for the reply. I didn’t make myself clear and sorry for the confusion.

Actually I want to make the WHERE condition dynamically without hard-coding. Something like:

public UserInfo getUserInfo(WhereDSL wdsl) {

	SelectStatementProvider sql = select(users.allColumns())
                .from(users)
                .applyWhere(wdsl)		//Parameterized, NOT hard coding.
                .build().render(RenderingStrategies.MYBATIS3);
	......	
}

And then I can search the “users” table with different search condition like the following:

UserInfo userA = getUserInfo(where(user.id, isEqualTo(1)));
UserInfo userB = getUserInfo(where(user.name, isLike("harry")));

The reason for this is that there are many scenarios to search the same table and return same columns with different search conditions. I don’t want to use WhereClauseProvider either because it requires me to create an extra mapper to support WhereClauseProvider. 

Do you have any suggestion about my issue?

**Comment by mobileharry** [comment]
Thank you for the reply, Jeff. It really solves my problem.

**Comment by mobileharry** [comment]
Thank you for the reply, Jeff. It really solves my problem.
