### ISSUE TITLE
Not support org.apache.ibatis.type.EnumOrdinalTypeHandler

### ISSUE THREAD

**Issue by xunyao4dev** [mybatis/mybatis-dynamic-sql#385]
SqlColumn.java
```
    protected String name;
    protected SqlTable table;
    protected JDBCType jdbcType;
    protected boolean isDescending;
    protected String alias;
    protected String typeHandler;
```
I think there should be a field named 'javaType'.
With this field, a sql generated will be `'select col1, col2 where col3=#{parameters.p1,jdbcType=CHAR,typeHandler=org.apache.ibatis.type.EnumOrdinalTypeHandler,javaType=com.example.MyEnum.class}'`, if this field does not exist, we cannot use EnumOrdinalTypeHandler directly.

**Comment by jeffgbutler** [comment]
Thanks for reporting this!
