### ISSUE TITLE
[Bug] The table aliases always the same when join the same table

### ISSUE THREAD

**Issue by blling** [mybatis/mybatis-dynamic-sql#390]
I join the same table twice with two different `tableAliases`, the final sql use the same aliases for the two table:

SelectStatementProvider：
![image](https://user-images.githubusercontent.com/26540808/131468176-f850812b-3cdb-4e6b-ab7b-7fa59b811d0b.png)

Sql:
![image](https://user-images.githubusercontent.com/26540808/131468850-e7200196-2f75-472f-abd6-6582d90f7fa7.png)

**Comment by blling** [comment]
@jeffgbutler

**Comment by jeffgbutler** [comment]
Not a bug. See here for an example of coding a self join (you need to create a second instance of the _menu_ SqlTable): https://github.com/mybatis/mybatis-dynamic-sql/blob/c8333e2e1befa2dce0992142bec7f32af7509603/src/test/java/examples/joins/JoinMapperTest.java#L916-L945

**Comment by blling** [comment]
O….OK.Seems a little strange:-(

**Comment by blling** [comment]
@jeffgbutler Thanks for your details. I have no ideas for now. 

I use `MyBatis Generator` to generate code of `MenuDynamicSqlSupport`, Maybe the `MenuDynamicSqlSupport` class should gennerate a Method like `MenuDynamicSqlSupport.newMenu()`.
