### ISSUE TITLE
Advise to create org.mybatis.dynamic.sql.select.QueryExpressionDSL.QueryExpressionWhereBuilder#orderBy overload with Collection

### ISSUE THREAD

**Issue by djechelon** [mybatis/mybatis-dynamic-sql#408]
After applying a where clause, the method chaining is returned a QueryExpressionWhereBuilder object

https://github.com/mybatis/mybatis-dynamic-sql/blob/3b8f288de8d2c25403eb1d032bfc4a1718bd6cc1/src/main/java/org/mybatis/dynamic/sql/select/QueryExpressionDSL.java#L253

There is only one overload of `orderBy` which takes a varargs array of arguments. It is advisable to add support for `Collection`.

Working example

```java
        Collection<SortSpecification> finalSorting;
        List<T> data = getMapper().select(row -> row
//                .applyWhere(....any....)
                .orderBy(finalSorting)
                .offset(offset)
                .fetchFirst(pageSize)
                .rowsOnly()
        );
```

After uncommenting the applyWhere, or any other `where`-like method, the code does not compile.
Yet, a workaround is to convert the collection to array

**Comment by jeffgbutler** [comment]
Thanks for reporting this - I will push a fix.
