### ISSUE TITLE
Fluently set table alias at runtime with a new instance

### ISSUE THREAD

**Issue by djechelon** [mybatis/mybatis-dynamic-sql#413]
This is a feature request **across** Mybatis Dynamic SQL and the generator.

With complex queries, it is easy that you have to reuse the same table with multiple aliases in the same query.
E.g. when you have to traverse joins multiple times or self-relationships

```
SELECT
FROM People people
JOIN People children ON children.parent = people.id
```

Thanks to Mybatis Generator, I have the SQLTable class for all my entities.

Request is to add a method to `SqlTable` that returns a copy of `this` with a different alias

```java
People people = PeopleDynamicSqlSupport.people.alias("people");
People children = PeopleDynamicSqlSupport.people.alias("children");
```

```java
select()
.from(people)
.join(children).on(children.parent, equalTo(people.id))
```

Currently, using `.join(people,"children")` makes ambiguous queries, or you have to construct the aliased SQL column in the query. Instantiating SQL tables as objects helps syntax being fluent.

Of course, thanks to Java inheritance it's not immediate to implement a method on the abstract class that returns an instance of the derived class, unless we abuse generics. Or if the generator provides a cast for us.

Please share your feedback and ask for additional questions if needed

**Comment by jeffgbutler** [comment]
Thanks for the idea! I'm very aware that table aliases are awkward with joins - self joins being particularly difficult. And it gets even more difficult with subqueries. Your idea may be a good way to address it, but it will require some fairly impactful changes. I'm going to experiment with it a bit.

**Comment by jeffgbutler** [comment]
I'm not sure what you mean here:

>Of course, thanks to Java inheritance it's not immediate to implement a method on the abstract class that returns an instance of the derived class, unless we abuse generics. Or if the generator provides a cast for us.

Can you elaborate?

**Comment by djechelon** [comment]
It means that if `SqlTable` class has a method signed `public SqlTable withAlias(String)` then it will return the superclass, and not the subclass.

With MBG, you'll be generating subclasses of `SqlTable` and the goal is to have their `withAlias` method return an instance of `this`, which is a subclass.

Two options:

1. Define generic `SqlTable`

```java
public class SqlTable<T extends SqlTable> {

    public T withAlias(String alias) {
        return (T) this;
    }

}
```

2. Have MBG extend the methods

public class UserDynamicSqlSupport {

    public static class UserTable extends SqlTable {

        public UserTable withAlias(String alias) {
            return this;
        }
    }

}

**Comment by jeffgbutler** [comment]
Got it. Thanks.
