### ISSUE TITLE
Why not support having?

### ISSUE THREAD

**Issue by blling** [mybatis/mybatis-dynamic-sql#418]
Is there any details why not support ‘having’?

And how to extend ‘Mybatis Dynamic SQL’ to support having?

**Comment by jeffgbutler** [comment]
No reason other than I haven't gotten around to implementing it yet. It's not trivial as it will need to implement and/or logic like we have in the where clauses. I've done some experimenting with it in the past, but not for some time now.

I'll leave this open as an enhancement request.
