### ISSUE TITLE
Is there a general way to automatically generate update time and creation time?

### ISSUE THREAD

**Issue by scxdhr1998** [mybatis/mybatis-dynamic-sql#465]
I try to modify the statement in the interceptor, is there a better way to do this?

**Comment by jeffgbutler** [comment]
A MyBatis interceptor is a good approach if you want to have the SQL modified in some global way without having to rely on coding in each statement. But an interceptor like that can be difficult to implement for all possible cases.

My personal preference would be to code the the statements with all the fields you need. There may be a bit of duplicated code, but I believe duplicated code is preferable to a complex abstraction in this case. YMMV.

**Comment by scxdhr1998** [comment]
thanks for your reply
