### ISSUE TITLE
How to make a  customized tableName

### ISSUE THREAD

**Issue by MaLuxray** [mybatis/mybatis-dynamic-sql#467]
In my case

``` java
  SelectStatementProvider statementProvider = select(id)
                .from(hisRecipe)
                .build().render(RenderingStrategies.MYBATIS3);
```
the sql like this

``` sql
  select id from his_recipe
```

Now i want to make `his_recipe`  with prefix, How do it

``` sql
  select id from prefix_his_recipe
```

**Comment by jeffgbutler** [comment]
You can create a SqlTable object with a Supplier - this would allow you to change the name on the fly.

I am also working on a better way to modify the generated SQL, but that will take a bit longer to finish.

**Comment by MaLuxray** [comment]
@jeffgbutler Thansk for you answer！

**Comment by MaLuxray** [comment]
I think the implementation of this problem can refer to the alias of the table.

``` java 
  select(id).from(table).prefix("p_").suffix("_s")
```

``` sql
   select id from p_table_s
```
