### ISSUE TITLE
Issues about table alise 1.4.0

### ISSUE THREAD

**Issue by clcy1243** [mybatis/mybatis-dynamic-sql#469]
at this version, when use generator 1.4.1, will generate table class extends `AliasableSqlTable`, with method `withAlias`

now here is problem, `withAlias` will return new table instance, but when use `select().from(table.withAlias('alias'))`, alias not working.   `select().from(table, 'alias')`, will work.

at class `AbstractQueryExpressionDSL`, method `addTableAlias`,  put alias into `Map<SqlTable, String> tableAliases`.

### problem 

 if use `withAlias` method, map key is new table instance, not equals origin table, so can't found alias for column, so how `withAlias` method work?

**Comment by jeffgbutler** [comment]
The `withAlias` method creates a new instance of `SqlTable`. For the alias to be applied, you will need to use column references from the new object (as you've seen, it doesn't work with the usage you show).

This is mainly designed to help with self joins. There's an example in the tests here: https://github.com/mybatis/mybatis-dynamic-sql/blob/bd5d3b5e8c82426c016e6a3daef2e55b287567d1/src/test/java/examples/joins/JoinMapperTest.java#L960-L989

**Comment by clcy1243** [comment]
thanks, I see.
