### ISSUE TITLE
[Feature Request]: Default function implementation for RowMapper

### ISSUE THREAD

**Issue by kcmvp** [mybatis/mybatis-dynamic-sql#476]
In practice, we implemented lots of RowMapper. those RowMappers are almost the same pattern. in the framework, there could be a graceful solution. let's take an example from the example code 
here is the code for query in **examples.spring.PersonTemplateTest**

```java
Buildable<SelectModel> selectStatement = select(id, firstName, lastName, birthDate, employed, occupation, addressId)
                .from(person)
                .where(id, isEqualTo(1))
                .or(occupation, isNull());

List<PersonRecord> rows = template.selectList(selectStatement, personRowMapper);

static RowMapper<PersonRecord> personRowMapper =
            (rs, i) -> {
                PersonRecord record = new PersonRecord();
                record.setId(rs.getInt(1));
                record.setFirstName(rs.getString(2));
                record.setLastName(LastName.of(rs.getString(3)));
                record.setBirthDate(rs.getTimestamp(4));
                record.setEmployed("Yes".equals(rs.getString(5)));
                record.setOccupation(rs.getString(6));
                record.setAddressId(rs.getInt(7));
                return record;
            };
```

as in the code **List<PersonRecord> rows = template.selectList(selectStatement, personRowMapper);** there are already information about the **SqlColumn**,  so it's feasible to get/figure out the corresponding value by "getXxxx()" by **column name**

With this functionality supports, in most the case no need to implement a **RowMapper** just using the **Default** implementation.

**Comment by jeffgbutler** [comment]
You can certainly do something like `record.setId(rs.getInt(id.getName()))`. This is what I'm doing more and more with Spring rather than using the indexes.

I'm not understanding how this would turn into something more generic that would allow you to skip the row mapping altogether. Can you give an example of what you're thinking?

**Comment by kcmvp** [comment]
> You can certainly do something like `record.setId(rs.getInt(id.getName()))`. This is what I'm doing more and more with Spring rather than using the indexes.
> 
> I'm not understanding how this would turn into something more generic that would allow you to skip the row mapping altogether. Can you give an example of what you're thinking?
> 
> (I do see how we could implement some kind of default row handler using a lot of reflection, but I am not really interested in doing a reflection based utility)

Yes, It's based on the reflection. From the point of proctivity it will save lots of time. especially for enterprise development among a team, of course it may be a bit performance(as reflection) degradation, but the framework can cache the mapping result. 

That's why I propose a **default** implementation, if you dont like the default implementation, you can just using the normal way. back to our case, if the framework support this feature, it will bring us lots of convenice and improve theam's  productivity greatly.

**Comment by kcmvp** [comment]
we have used both **mybatis & mybatis-dynamic-sql** in practice. The main reason I adopt ** mybatis-dynamic-sql** is that we  like using java-style(DSL style) to write **sql**. I will reduce the opportunities to make silly mistakes. The over all feeling of using **mybatis-dynamic-sql** is that it will improve the productivity of the team greatly if the framework supplies some level **auto RowMapper**(in fact 90% of the sql is simple in a project, at least my case).  in fact traditional **Mybatis** support this.

**Comment by kcmvp** [comment]
by the way, the two **[Feature Reuest]** are what we want most features. Thank you great work. Let keep the framework evolving  continuously.

**Comment by kcmvp** [comment]
> I think it would be difficult to code such a thing, but I'll think about it for a bit.
> 
> I have also considered adding function to MyBatis Generator to generate code for Spring - so there could be a generated rowMapper and CRUD operations. Maybe that would be a better route to take?

Implement it with code generation is a solution. if use this way, then it will need additional step during daily development(may be via maven-plugin, gradle-plugin). I fact I am also using some how the same thoughts to improve teams productivity. To tell the truth the whole team does not like it. The feedback I got most is additional step means additional mental afford.

**Comment by jeffgbutler** [comment]
It occurred to me that, of course, Spring already includes default row mappers that will work for this usage (`BeanPropertyRowMapper` and `DataClassRowMapper`). I've added a couple of examples in #478

**Comment by kcmvp** [comment]
👍

**Comment by jeffgbutler** [comment]
Closing this request as Spring already includes default row mappers.
