### ISSUE TITLE
Does it support batch insert ?

### ISSUE THREAD

**Issue by ma-xiao-guang-64** [mybatis/mybatis-dynamic-sql#53]
like this INSERT INTO table (id, name) VALUES (?, ?), (?, ?)

**Comment by jeffgbutler** [comment]
Batch insert is supported with the help of MyBatis batch support. See this page for an example: http://www.mybatis.org/mybatis-dynamic-sql/docs/insert.html

**Comment by ma-xiao-guang-64** [comment]
Thanks, i know this, but i want to use that like INSERT INTO table (id, name) VALUES (?, ?), (?, ?), (?, ?), (?, ?), (?, ?)

**Comment by ma-xiao-guang-64** [comment]
ok, i know how to use it!

**Comment by jeffgbutler** [comment]
For anyone looking at this issue, here is an update...

I've been looking into this a bit. It is not too difficult to add the ability to generate a multi-row insert statement like this. However, it is difficult to execute these kinds of statements in MyBatis if you expect to retrieve generated keys.  And in fact, MyBatis is changing how this will work in the next major version (https://github.com/mybatis/mybatis-3/pull/1249)

So I don't expect to make any changes in this area until the new MyBatis version is out at the very least.

I do continue to believe that insert statements like this are generally not a good idea. There are so many traps and limitations that I am very cautious about adding support for them into a general purpose library. Using the current batch support, as described above, will be the recommended approach for now.

**Comment by luozhenyu** [comment]
When I follow the document and write some codes which has inserting statement in loops, I have a performance problem. It takes about 10 seconds to insert just 10,000 records.

So I do expect there will be some ways to improve this situation. 

> Thanks, i know this, but i want to use that like INSERT INTO table (id, name) VALUES (?, ?), (?, ?), (?, ?), (?, ?), (?, ?)

I think it could be a practical way to improve performance of batch inserting.

**Comment by jeffgbutler** [comment]
It is very unlikely that a multi-insert will perform faster than a batch. And it would probably not work to insert 10,000 records with a multi-insert anyway - you would hit the JDBC parameter limit.

So I think it is likely that there is something wrong in your BATCH configuration. Two things are important:

1. Make sure that when you open the SQL Session, you set the executor type to BATCH
1. Make sure you have transaction support properly configured. If you are using Spring, you might be interested in this conversation: https://github.com/mybatis/spring/issues/364

There is a full example in this test: https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/generated/always/mybatis/GeneratedAlwaysAnnotatedMapperTest.java
