### ISSUE TITLE
how to self join

### ISSUE THREAD

**Issue by ether007** [mybatis/mybatis-dynamic-sql#54]
when self join
SelectStatementProvider q = select(id, name) .from(UserDynamicSqlSupport.user,"u1") .leftJoin(UserDynamicSqlSupport.user2,"u2").on(UserDynamicSqlSupport.user2.pid,equalTo(id)) .where(id, isGreaterThan(1)) .build() .render(RenderingStrategy.MYBATIS3);
generator sql is
select u2.id, u2.name from t_user u2 left join t_user u2 on u2.id = u2.pid where u2.id > ?

**Comment by jeffgbutler** [comment]
I understand the issue and will work on a fix.

**Comment by carzyhub** [comment]
How do I use self Join in Kotlin
