### ISSUE TITLE
SqlBuilder.concatenate parse problem

### ISSUE THREAD

**Issue by tzengshinfu** [mybatis/mybatis-dynamic-sql#568]
Firstly thank you very much to build such useful framework. I am using it in my project.
I have a use case for table updating in MySQL 8.0.28. eg:

```
var updateTableDSL = SqlBuilder
                .update(Table)
                .set(Table.textColumn)
                .equalTo(SqlBuilder.concatenate(Table.textColumn, SqlBuilder.stringConstant("someText")))
                .where(Table.PrimaryKey, isEqualTo("thePrimaryKey"));
var updateTableStatement = updateTableDSL.build().render(RenderingStrategies.MYBATIS3);

updateTableStatement.getUpdateStatement(); // print parsed sql syntax
"update Table set textColumn = (textColumn || 'someText') where Primarykey = #{parameters.p1,jdbcType=VARCHAR}"
```

It retuns an error:Truncated incorrect DOUBLE value

Because MySQL uses 'concat' function for string concatenation and doesn't support '||'.
In most databases(Oracle, SQLServer, DB2...), they use 'concat' function to concatenate strings.
PS:SQLite uses '||' and MS Access uses '&'

If the 'SqlBuilder.concatenate' can be parsed to 'concat()', then it can used in most databases.

Thank you!

**Comment by jeffgbutler** [comment]
@tzengshinfu thanks for reporting - I'm glad you are finding value from the library!

I'll add a new function for `concat`, but you can do it yourself in the meantime. The library is very extensible and it is easy to to implement new functions. See this doc page for details: https://mybatis.org/mybatis-dynamic-sql/docs/extending.html#abstractunitypefunction-example
