### ISSUE TITLE
How to cast the column to postgres type upon writes?

### ISSUE THREAD

**Issue by ktalebian** [mybatis/mybatis-dynamic-sql#584]
I am using a postgres typed column for my table `user`. Reading data is fine, but when I try to update/insert, I get the following exception

```
org.postgresql.util.PSQLException: ERROR: column "role" is of type user_role but expression is of type character varying
```

I basically need to do a `cast(role as user_role)` on the insert statement. How can this be accomplished?

**Comment by jeffgbutler** [comment]
Two suggestions:

If it will work with a type handler, then define the type handler in the column definition and it will be applied on the write. For example:

```java
SqlColumn<String> role = column("role", JDBCtype.VARCHAR, "foo.MyTypeHandler"); 
```

If you need to do the cast, then you can write your own cast function. I tried to make the library very easy to extend for situations like this. Documentation about writing functions is here: https://mybatis.org/mybatis-dynamic-sql/docs/extending.html#writing-custom-functions

**Comment by ktalebian** [comment]
@jeffgbutler how do I do this via the mybatis-config.xml file? I can manually override this but upon next generation, the change will be removed. This is what I have right now:

```
<table schema="public" tableName="user" delimitIdentifiers="true">
        <columnOverride column="role" javaType="com.app.types.UserRole" typeHandler="com.app.handlers.UserRoleTypeHandler" />
</table>
```

This correctly defines the `@Result` mapping, but the `UserDynamicSqlSupport` file does not have the `column("role", JDBCtype.VARCHAR, "foo.MyTypeHandler"); `

**Comment by ktalebian** [comment]
@jeffgbutler thank you! That worked!
