### ISSUE TITLE
Dynamic SQL does not work with harcoded where clauses

### ISSUE THREAD

**Issue by ktalebian** [mybatis/mybatis-dynamic-sql#588]
Here is a simple example:

```java
 @SelectProvider(type = UserRepository.Statements.class, method = "selectById")
Optional<User> selectById(final Long id);

class Statements {
    public String selectByPrimaryKey(final Long id) {
      return MyBatis3Utils.select(
              selectList, user, c -> c.where(UserDynamicSqlSupport.id, isEqualTo(id)))
          .getSelectStatement();
    }
```

This works great. Now, let me modify it slightly:

```java
 @SelectProvider(type = UserRepository.Statements.class, method = "selectById")
Optional<User> selectById(final Long id);

class Statements {
    public String selectByPrimaryKey(final Long id) {
      return MyBatis3Utils.select(
              selectList, user, c -> c.where(UserDynamicSqlSupport.id, isEqualTo(id)).and(UserDynamicSqlSupport.role, isEqualTo(UserRole.Admin))
          .getSelectStatement();
    }

// Separately, I have defined the `public class UserRoleTypeHandler extends BaseTypeHandler<UserRole>` for both set and get for this role
```

Now, this no longer workers. Here is the error:

```text
The error occurred while setting parameters ### SQL: select id, username, email, role from "public"."user" where role = ? ### Cause: org.postgresql.util.PSQLException: ERROR: operator does not exist: user_role = character varying Hint: No operator matches the given name and argument types. You might need to add explicit type casts. Position: 365 ; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: operator does not exist: user_role = character varying Hint: No operator matches the given name and argument types. You might need to add explicit type casts. Position: 365
```

If I tail the query logs, I see:

```
ERROR:  operator does not exist: user_role = character varying at character 365
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  select id, username, email, role from "public"."user" where role = $1
```

Now, if I change the code above to be:
```java
 @SelectProvider(type = UserRepository.Statements.class, method = "selectById")
Optional<User> selectById(final Long id, final UserRole userRole);

class Statements {
    public String selectByPrimaryKey(final Long id, final UserRole userRole) {
      return MyBatis3Utils.select(
              selectList, user, c -> c.where(UserDynamicSqlSupport.id, isEqualTo(id)).and(UserDynamicSqlSupport.role, isEqualTo(userRole))
          .getSelectStatement();
    }
```

Then this _does_work - in the query logs I now see:

```
STATEMENT:  select id, username, email, role from "public"."user" where role = $1
DETAIL:  parameters: $1 = 'Admin'
```

There is the extra `parameters: $1 = 'Admin'` set. What's going on? How can I write my query without providing this extra parameter as an input parameter?

**Comment by jeffgbutler** [comment]
@ktalebian The main issue I can see is that you are ignoring the parameters map that matches the generated statement. The `SelectStatementProvider` contains both a generated statement and a matching set of parameters and these should be used together. MyBatis can figure this out when there is only one parameter, but when you add a second condition then you must use the matched parameters map.

There is a built in class `SqlProviderAdapter` that knows how to use both parts of the generated statement. You can use it like the following.

```java
interface UserMapper {
  @SelectProvider(type=SqlProviderAdapter.class, method="select")
  Optional<User> selectOne(SelectStatementProvider selectStatement);
}

class Statements {
  public Optional<User> selectByPrimaryKey(final Long id, final UserRole userRole) {
    return MyBatis3Utils.selectOne(UserMapper::selectOne,
              selectList, user,
              c -> c.where(UserDynamicSqlSupport.id, isEqualTo(id))
                     .and(UserDynamicSqlSupport.role, isEqualTo(userRole));
    }
}
```

You could also add default methods in the mapper that do the same if you don't need the separate `Statements` class.

**Comment by ktalebian** [comment]
@jeffgbutler your example is sitll providing `userRole` as an input parameter to the function, i.e. the use of this would be `. selectByPrimaryKey(userId, UserRole.Admin)`. I want the `UserRole` to be constant - just do `. selectByPrimaryKey(userId)`. In other words, I want to have `getAdminUesr(userId)` for example.

**Comment by jeffgbutler** [comment]
Maybe this:

```java
public Optional<User> getAdminUser(final Long id) {
    return MyBatis3Utils.selectOne(UserMapper::selectOne,
              selectList, user,
              c -> c.where(UserDynamicSqlSupport.id, isEqualTo(id))
                     .and(UserDynamicSqlSupport.role, isEqualTo(stringConstant("admin")));
    }
```

**Comment by jeffgbutler** [comment]
No response - assuming this is resolved.

**Comment by ktalebian** [comment]
@jeffgbutler thanks this worked, but now I have another problem.

This does not work:

```java
@SelectProvider(type = UserRepository.Statements.class, method = "selectEmails")
Optional<List<String>> selectEmails(final String domain);

class Statements {
    public String selectEmails(final String domain) {
      return MyBatis3Utils.select(
            BasicColumn.columnList(email),
            user,
            q ->
                q.where(role, isEqualTo(UserRole.Owner))
                    .and(status, isEqualTo(UserStatus.Active))
                    .and(email, isLike("%" + domainName))
        ).getSelectStatement();
    }
}
```

Note that this is the `UserMapper` but the response is not a `User` but rather a `List<String>`. I understand the problem is that I am returning `.getSelectStatement();` and not the mapped parameters, but I do not know how to write the query so that it returns a different type other than a User from this mapper class.

**Comment by jeffgbutler** [comment]
The mapper shouldn't return `Optional<List<String>>`, it should return `List<String>`. The list will be empty if no records match.

And, of course, this will still fail because you are not using the matched parameters. Please consider using the library as I showed in my example above.

Additionally, we supply generic mappers that will work for this case. If you register `CommonSelectMapper` in your MyBatis configuration, then you can use the method `CommonSelectMapper::selectManyStrings` for this query if you will use the library as shown in my example.
