### ISSUE TITLE
Unable to automatically update ID propery using autogenerated insert() method

### ISSUE THREAD

**Issue by AlexOreshkevich** [mybatis/mybatis-dynamic-sql#61]
I'm using mybatis generator with target runtime MyBatis3DynamicSql and ANNOTATEDMAPPER java client generator options.

Previously I had the following insert() annotated method (manually written):

```
@Insert({"insert into header (create_date, modify_date, dealID, timestamp, orgId, ecmHeadFolder) VALUES (#{createDate}, #{modifyDate}, #{dealid}, #{timestamp}, #{orgid}, #{ecmheadfolder})"})
@Options(useGeneratedKeys=true, keyColumn = "id")
void simpleInsert(Header header);
```

In this case Header was supplied with a proper ID property right after insert() method call which was desired behavior. Header entity has a Long id field that is mapped like `id BIGSERIAL PRIMARY KEY`.

Now I try to use autogenerated mappers and dynamic SQL approach. After generation I received insert() method with the following implementation (`@Options` were added later, manually):

```
@InsertProvider(type=SqlProviderAdapter.class, method="insert")
@Options(useGeneratedKeys=true, keyColumn = "id")
int insert(InsertStatementProvider<Header> insertStatement);
```

I expected that either insert will return ID after insertion (tried to use long) or it will update ID field in the entity class automatically (like it was before or like it happens for the XML based implementation)

`<insert id="insert" useGeneratedKeys="true" keyProperty="id" keyColumn="id">`

Nothing expected happened and new autogenerated insert() method simply returns number of updated rows (created in our case).

Please suggest me a way how to achieve automatic ID set for entity using autogenerated keys using autogenerated mappers.

PS Tried @SelectKey using nextval() and id sequence, didn't help.

**Comment by jeffgbutler** [comment]
This is probably an issue with the generator and not the dynamic SQL library. The annotation should look like this:

```java
@Options(useGeneratedKeys=true, keyColumn = "record.id")
```
(Note `record.id` and not `id`) The generator should create this annotation properly, but I can think of an instance where this might happen...

1. The class previously existed
1. The class was originally generated for the old MyBatis3 runtime
1. You are running in Eclipse and the code went through the Java code merger

Does this describe your situation?  If so, just change the keyColumn to `record.id` and all should be well.

**Comment by jeffgbutler** [comment]
No response. Assuming this is resolved.

**Comment by 411937647** [comment]
I have the same problem.
I tried what you said, but it didn't work, but I found a solution.
` @Options(useGeneratedKeys=true, keyColumn = "id",keyProperty="record.id")`
Note that attribute keyProperty instead of keyColumn.

**Comment by jeffgbutler** [comment]
@411937647 - thanks - you are correct. `keyProperty` is the correct attribute.

**Comment by AlexOreshkevich** [comment]
Hi guys, sorry for late response.

The issue was in mybatis generator settings first of all. I had to specify allowance for autogenerated columns usage as following (inside `<table>` config section):

`<generatedKey column="id" sqlStatement="JDBC" identity="true" type="post"/>`

This was leading to the following annotation in generated Mapper interface:

`@Options(useGeneratedKeys=true,keyProperty="record.id")`

BY the way, make sure that you are using sequence on the PostgreSQL side. It means `SERIAL` or `BIGSERIAL` datatype for `id` field.

Works like a charm.
