### ISSUE TITLE
关于对空间数据操作sql拼接

### ISSUE THREAD

**Issue by liuyukuai** [mybatis/mybatis-dynamic-sql#626]
eg：SELECT *  FROM table where ST_Within(ST_GeomFromText(?,4326), geom) ;

这种sql应该如何拼接呢？

**Comment by jeffgbutler** [comment]
You should be able to write custom functions for this. See the docs here: https://mybatis.org/mybatis-dynamic-sql/docs/extending.html#writing-custom-functions

**Comment by DaZuiZui** [comment]
您好，还可以更详细一点吗？ 目前的对此了解到的解决方案
 can you be more detailed? Current known solutions to this
`<select id="debugTest1" parameterType="String" resultType="UrResultType">
  SELECT * FROM table
  WHERE
    <if test="urval != null">
      ST_Within(ST_GeomFromText(#{urval}, 4326), geom)
    </if>
    <if test="urval == null">
       -- 处理空数据的逻辑 
       -- Logic to handle empty data
    </if>
</select>`

**Comment by jeffgbutler** [comment]
No response
