### ISSUE TITLE
Does it support @one or @many annotation?

### ISSUE THREAD

**Issue by 411937647** [mybatis/mybatis-dynamic-sql#63]
Thank you for checking.
Here is my question.
For example, order table  has a field userid,and I need the order info and  user info in the user table at the same time.
I tried to do like this.
`@Result(column="userid", property="userid", jdbcType=JdbcType.BIGINT, one=@One(select="com.xxx.dao.UserMapper.selectByPrimaryKey",fetchType=FetchType.LAZY)`
defined attribute user in model class 'Order'
`private User user;`
It doesn't work.
What should I do?

**Comment by jeffgbutler** [comment]
The `@One` annotation should work. Your property should be `user` in this case.

`@Many` won't work directly with code generated by MyBatis generator, but you could write utility methods that would work.

**Comment by jeffgbutler** [comment]
No response.
