### ISSUE TITLE
Support for custom rendering conditions 

### ISSUE THREAD

**Issue by JustZzzxf** [mybatis/mybatis-dynamic-sql#64]
In the latest version, only simple rendering condition judgments are supported, such as IsEqualToWhenPresent for non-null values.However, for String types, in some cases we expect not only non-null, but also non-empty can not be rendered, such as front-end query parameters, empty String means unconditional. So, i hope the SqlBuilder can  support  custom rendering conditions . The example i used now:

```
public class IsEqualToIf<T> extends IsEqualTo<T> {

    private Predicate<T> renderCondition;

    protected IsEqualToIf(Supplier<T> valueSupplier, Predicate<T> renderCondition) {
        super(valueSupplier);
        this.renderCondition = Objects.requireNonNull(renderCondition);
    }

    @Override
    public boolean shouldRender() {
        return renderCondition.test(value());
    }

    public IsEqualToIf<T> of(Supplier<T> valueSupplier, Predicate<T> renderCondition) {
        return new IsEqualToIf<>(valueSupplier, renderCondition);
    }
}
```

```
public class IsEqualToIfNotEmpty extends IsEqualToIf<String> {

    protected IsEqualToIfNotEmpty(Supplier<String> valueSupplier, Predicate<String> renderCondition) {
        super(valueSupplier, renderCondition);
    }

    public static IsEqualToIfNotEmpty of(String value) {
        return new IsEqualToIfNotEmpty(() -> value, val -> val != null && !"".equals(val.trim()));
    }
}

```

**Comment by jeffgbutler** [comment]
Thanks - I like this idea very much. I will build this into the library.

**Comment by jeffgbutler** [comment]
I've got an initial implementation of this in my branch here: https://github.com/jeffgbutler/mybatis-dynamic-sql/tree/new-conditionals There is documentation here: https://github.com/jeffgbutler/mybatis-dynamic-sql/blob/new-conditionals/src/site/markdown/docs/conditions.md

It is a bit different from what you suggested - I use the name `IsEqualToWhen` rather then `IsEqualToIf`, but other than that it is basically the same.

I haven't decided on the syntax for the `In` and `NotIn` conditions yet, so they are not implemented.

I am very interested in feedback on this. Please feel free to check it out and let me know if you have any suggestions.

**Comment by jeffgbutler** [comment]
I've made a change to the syntax that, I think, is better. The conditions now support a `when` method. So you can code something like this: `where(foo, isEqualTo(bar).when(Objects::notNull))`

**Comment by JustZzzxf** [comment]
> I've got an initial implementation of this in my branch here: https://github.com/jeffgbutler/mybatis-dynamic-sql/tree/new-conditionals There is documentation here: https://github.com/jeffgbutler/mybatis-dynamic-sql/blob/new-conditionals/src/site/markdown/docs/conditions.md
> 
> It is a bit different from what you suggested - I use the name `IsEqualToWhen` rather then `IsEqualToIf`, but other than that it is basically the same.
> 
> I haven't decided on the syntax for the `In` and `NotIn` conditions yet, so they are not implemented.
> 
> I am very interested in feedback on this. Please feel free to check it out and let me know if you have any suggestions.

Pretty good. :) Does the latest version support this feature? I checked that the latest version in the Maven repository was still 1.1.0.

**Comment by jeffgbutler** [comment]
I expect to release this in early January.
