### ISSUE TITLE
custome SqlColumn can equals *SqlSupport sqlColumn,  Determine whether this field exists in the table

### ISSUE THREAD

**Issue by pondered** [mybatis/mybatis-dynamic-sql#642]
custom SqlColumn  determine if it exists in table. 
i think *SqlSupport  add fields COLUMNS all column with unmodifyableList

SqlColumn add equals method

example:
```java
public final SqlColumn<Long> id = column("id", JDBCType.BIGINT);
public final List<SqlColumn<Object>> COLUMNS = Collections.unmodifiableList(new ArrayList() {{
            add(id);
        }});

COLUMNS.forEach(column->column.name().equals(SqlCoumn.of("id"))) // return true 
```

**Comment by pondered** [comment]
or `SqlColumn.of(column,table)`   check  column Is it in the table?

**Comment by jeffgbutler** [comment]
I don't fully understand your request, but I will say that we don't want to add an `equals` method to `SqlColumn`. It was in the library in an early version, but it made self joins difficult.

**Comment by pondered** [comment]
like this:
i have a table, 
(id,description)

```
SqlColumn.of("x",table) // not exists    exception? 
```
or 
```kotlin
Columns(id,description).for{
   it.equals(SqlColumn.of("id", table)) // exists true
   it.equals(SqlColumn.of("x", table)) // not exists  false
}

```

**Comment by jeffgbutler** [comment]
What problem are you trying to solve? These little code snippets are not helpful without some context.

**Comment by pondered** [comment]
sorry, Check whether a field is in the table to prevent invalid SQL from being generated and cause exceptions

**Comment by jeffgbutler** [comment]
You could write a name based comparitor if you have this issue. As I said, we will not add an `equals` method to `SqlColumn`.

**Comment by pondered** [comment]
thx
