### ISSUE TITLE
multiple insert selective?

### ISSUE THREAD

**Issue by pondered** [mybatis/mybatis-dynamic-sql#644]

**Comment by jeffgbutler** [comment]
I don't think this is practical. You could end up with invalid SQL like this:

```sql
insert into foo (id, description) values (1, 'Text1'), (2), ('Text3')
```

**Comment by pondered** [comment]
i use db default value,  use mybatis plus strategy?
like this:
1. insert into foo (id, description) values (1, 'Text1'), (2), ('Text3') // exception
2. insert into foo (id, description) values (1, 'Text1'), (2,'Text2') // success
3. insert into foo (id, description) values (1, 'Text1'), (2,'Text2','2') // exception

**Comment by jeffgbutler** [comment]
We purposely prevent generation of invalid SQL in the library so we won't generate SQL that we know will cause an exception.

You could filter your input records and check for valid values before doing the insert multiple, or you could use regular insert selective statements.

**Comment by pondered** [comment]
thx
