### ISSUE TITLE
The default implementation of SelectStatementProvider that supports direct input of SQL string

### ISSUE THREAD

**Issue by mmm8955405** [mybatis/mybatis-dynamic-sql#649]
The default implementation of SelectStatementProvider that supports direct input of SQL string:

------
For example:
String sql = "select * from tabal";

SelectStatementProvider provide = new SelectStatementProvider(sql, parg);

mapper.select(provide );

Or there is a simpler way to directly pass in SQL string parameters:

String sql = "select * from tabal";

mapper.selectSQL(sql);

**Comment by mmm8955405** [comment]
This facilitates users to directly concatenate SQL statements in the code. 
[https://blog.jooq.org/using-java-13-text-blocks-for-plain-sql-with-jooq/](url)

**Comment by jeffgbutler** [comment]
You can do it like this:

```java
String sql = "select * from table";

SelectStatementProvider provider = SelectStatementProvider.withSelectStatement(sql).build();

mapper.select(provider);
```

**Comment by mmm8955405** [comment]
> You can do it like this:
> 
> ```java
> String sql = "select * from table";
> 
> SelectStatementProvider provider = SelectStatementProvider.withSelectStatement(sql).build();
> 
> mapper.select(provider);
> ```

Very excellent, I like it
