### ISSUE TITLE
lombok support needed

### ISSUE THREAD

**Issue by kid1412621** [mybatis/mybatis-dynamic-sql#65]
getter setter is damn

**Comment by jeffgbutler** [comment]
There is a plugin for lombok: https://github.com/mybatis/generator/wiki/Third-Party-Tools

**Comment by jeffgbutler** [comment]
I don't think so, but I'm not a lombok user so I don't know for sure. Try it and see! If you don't like what happens, then you can write your own plugin to make it work exactly as you want it to.
