### ISSUE TITLE
join return object?

### ISSUE THREAD

**Issue by pondered** [mybatis/mybatis-dynamic-sql#659]
i use mybatis dynamic use `join`/`left join`
Is there any way to return an object ?

[MyBatis3DynamicSql how generate xml file?](https://github.com/mybatis/generator/issues/1051)

**Comment by jeffgbutler** [comment]
Yes - you will need to create a class that matches the rows your query will generate, and also create a result map.

You could also use the `CommonSelectMapper` to return a Map for any query and then convert the Map to your specific object in code.

This is a basic MyBatis usage question. Please read the MyBatis documentation here: https://mybatis.org/mybatis-3/
