### ISSUE TITLE
DefaultUpdateStatementProvider How to obtain data？

### ISSUE THREAD

**Issue by 3237704136** [mybatis/mybatis-dynamic-sql#698]
DefaultUpdateStatementProvider How to obtain data？
Use mybatis-dynamic-sql + Mybatis Interceptor，When executing modification actions in SQL statements，arg[1] is DefaultUpdateStatementProvider ，However DefaultUpdateStatementProvider not having getRow() or getRandow()，IF my want get arg[1] data，What should I do？
![2](https://github.com/mybatis/mybatis-dynamic-sql/assets/43770682/3de0ac42-2a22-4b31-8223-a161e041706f)

**Comment by 3237704136** [comment]
![Uploading 2.png…]()

**Comment by 3237704136** [comment]
![2](https://github.com/mybatis/mybatis-dynamic-sql/assets/43770682/92090e79-c48c-41e8-95ed-bae605a3dfd9)

**Comment by jeffgbutler** [comment]
Update statements have a Map of parameters - not a matched row. You can access the Map like this:

```java
Map<String, Object> parameters = ((UpdateStatementProvider) args[1]).getParameters();
```

Once you have the Map, you can add or modify values as needed.

**Comment by 3237704136** [comment]
> Update statements have a Map of parameters - not a matched row. You can access the Map like this:
> 
> ```java
> Map<String, Object> parameters = ((UpdateStatementProvider) args[1]).getParameters();
> ```
> 
> Once you have the Map, you can add or modify values as needed.

Thank you, but I need the object to do some specific functions on my end. I need to implement the function of automatically filling in the time, and I need to determine whether there are creation time and modification time fields in the table. I need a standard, which is the Po model. However, the interface does not pass this model. I would like to see if there are other methods available
