### ISSUE TITLE
How to feed Dynamic fields for dynamic queries and JSONB fields

### ISSUE THREAD

**Issue by venkata-subbarao** [mybatis/mybatis-dynamic-sql#72]
This is not an issue. Rather I am seeking help. Apologies, if this is not the right platform to ask questions.

SelectStatementProvider example provided in Mybatis website starts as follows.

SelectStatementProvider selectStatement = select(id, animalName, bodyWeight, brainWeight)

If the fields are not known in advance and fields are available as list of String parameter from a class, how can I fill that in the above select(...) ?
Also, I am using PostgreSQL with JSONB column. How can I use JSONB field in the select(....) ?

I know how to select JSOB field using plain SQL statements. But, not sure whether SelectStatementProvider supports it.

**Comment by jeffgbutler** [comment]
There is a new feature (not released quite yet) where you can do a "select *" - that might meet your need. Take a look at this test - it selects all columns into a List<Map<String, Object>>: https://github.com/mybatis/mybatis-dynamic-sql/blob/7969f39975d31db7073c3680e0b49af7a9dcdaa4/src/test/java/examples/animal/data/AnimalDataTest.java#L112-L129

As for the JSONB question, I think that is a very different question and it should be in a different issue. But the first thing of importance will be to know how to make it work in MyBatis.

**Comment by jeffgbutler** [comment]
No response
