### ISSUE TITLE
Support for return type List<Map<String,Object>>

### ISSUE THREAD

**Issue by 411937647** [mybatis/mybatis-dynamic-sql#73]
When I need a multi-table query, I have to define the fields of one entity class in the other entity class, which is quite inconvenient.
Is it possible to provide a method that returns type  `List<Map<String,Object>>` in Mappers?
the corresponding XML looks like this:
```
<select id=”selectMany” resultType=”java.util.HashMap”>  
    select * from table
</select>  
```

**Comment by MaoZiYang** [comment]
This is perfectly possible.
If you need to return Map<String,Object>,You need to customize <result> 
You can compare the difference between resulttype and resultmap.

**Comment by jeffgbutler** [comment]
As @MaoZiYang say, it is possible now to return List<Map<String,Object>>. Also, I have recently added the ability to do the "select *" part of the request. It is not released yet, but soon. This test shows how it works:

https://github.com/mybatis/mybatis-dynamic-sql/blob/7969f39975d31db7073c3680e0b49af7a9dcdaa4/src/test/java/examples/animal/data/AnimalDataTest.java#L112-L129

Let us know if this will work for you.

**Comment by 411937647** [comment]
Thanks for your reply. My problem has been solved.
It would be more convenient if the MyBatis Generator generated methods that contain this return type.

**Comment by DanielLiu1123** [comment]
> It would be more convenient if the MyBatis Generator generated methods that contain this return type.

I feel the same way. `generalSelect` is useful when you want to do some grouping operations.
