### ISSUE TITLE
Enhance to support spring-batch integration

### ISSUE THREAD

**Issue by surrettcharles** [mybatis/mybatis-dynamic-sql#75]
I am trying to leverage this library for a spring-batch based project. While many of the examples work for traditional invocations, the way Spring-Batch calls function cause the behavior to be a little different.

I'm not sure where these enhancements would be best suited based on the dependencies they would bring in, but I will suggest they be added here and let the maintainers determine which library/libraries they should be absorbed into.

After much trial and error, here are the classes, and tweaks to the examples that need to be added to make the integrations work:
* `SqlProviderAdapter` needs to have the method parameters annotated with `@Param`. I chose `statement` for the parameter name, but whatever is chosen needs to also be used in the example. This is needed so the batch item reader properly passes the statement to the mapper and the provider class call.
```java
import org.apache.ibatis.annotations.Param;
import org.mybatis.dynamic.sql.select.render.SelectStatementProvider;
import org.mybatis.dynamic.sql.util.SqlProviderAdapter;

public class BatchSqlProviderAdapter extends SqlProviderAdapter
{
	@Override
	public String select(@Param("statement") SelectStatementProvider selectStatement)
	{
		return super.select(selectStatement);
	}
}
```
* The example for `SimpleTableMapper` would be updated to have the select method parameters also annotated with `@Param("statement")`
* The `MyBatisCursorItemReader<T>` needs an extension class that looks like this:
```java
import java.util.HashMap;
import java.util.Map;

import org.mybatis.dynamic.sql.select.render.SelectStatementProvider;
import org.mybatis.spring.batch.MyBatisCursorItemReader;

public class MyBatisDynamicCursorItemReader<T extends Object> extends MyBatisCursorItemReader<T>
{
	@Override
	public void setParameterValues(Map<String, Object> parameterValues)
	{
		Map<String, Object> parameters = new HashMap<>();
		
		parameters.putAll(parameterValues);
		
		if(parameterValues.containsKey("statement"))
		{
			SelectStatementProvider statement = (SelectStatementProvider)parameterValues.get("statement");
			parameters.put("parameters", statement.getParameters());
		}
		
		super.setParameterValues(parameters);
	}
}
```

I've put together a very simple example project [here](https://github.com/surrettcharles/dynamicSqlBatch)

**Comment by jeffgbutler** [comment]
Thanks for this detailed report! I will look into this, but it won't be for a few days.

**Comment by jeffgbutler** [comment]
@surrettcharles I understand this issue better now. I believe we need to make a change in mybatis-spring to make this work. Do you mind if I fork your example repo and send you some pull requests to show you what I'm thinking?

**Comment by jeffgbutler** [comment]
After looking at this a bit more, I decided to make some utility classes in this library to enable integration with Spring batch. I found there's not an easy way to change mybatis-spring and keep consistency with how that library works.

You can see the test case in my branch here: https://github.com/jeffgbutler/mybatis-dynamic-sql/tree/spring-batch/src/test/java/examples/springbatch

Please let me know if you have any comments about how this works. I still need to write some documentation for it. I think this is a decent solution even if it is a bit of coding around the way mybatis-spring works.

**Comment by surrettcharles** [comment]
Sorry for not checking in on this sooner. Your solution looks like a reasonable approach. Mine was a "hack-and-slash until it works" to show how to get around the issue I was seeing. Any idea when `1.1.1` will be released?
