### ISSUE TITLE
How to implement CASE WHEN THEN ELSE END statement?

### ISSUE THREAD

**Issue by mayamoon** [mybatis/mybatis-dynamic-sql#757]
I using mybatis-dynamic-sql to write sql , after investigate the sourse code i can't find a way to implement 
CASE 
WHEN condition THEN  value 
WHEN condition THEN  value 
ELSE value 
END

**Comment by jeffgbutler** [comment]
Case expressions aren't supported currently. I will look at adding some basic support for them.
