### ISSUE TITLE
When using groupBy, where{} OR having{} will be wrong!

### ISSUE THREAD

**Issue by wenlongwanggithub** [mybatis/mybatis-dynamic-sql#765]
I've been here for quite a while and don't know why.  When using groupBy and ‘where OR having’ has a filter，there will be some error as below. And only pure groupBy without 'where or having' filter ， it will be ok. But you know fitlers are quite necessary. So anybody helps me.

SQL in the first photo works in navicat, and the next dynamic SQL is absoulutely the same, but error.

![image](https://github.com/mybatis/mybatis-dynamic-sql/assets/76580062/a1278741-990f-4b2b-938f-41e97f57838b)

<img width="811" alt="image" src="https://github.com/mybatis/mybatis-dynamic-sql/assets/76580062/a999482b-1171-4e5f-9228-1e980ea3bd54">

<img width="1588" alt="image" src="https://github.com/mybatis/mybatis-dynamic-sql/assets/76580062/0784ff87-b5c1-49db-83ea-d68ea6386f26">

**Comment by jeffgbutler** [comment]
Please send actual code and log entries, not images. It is impossible to search images.

But, from what I can see, the generated code is not exactly the same as your navicat example, and there's a sub-query in the generated code that doesn't match the Kotlin code - `select count(0) from (select...`

Please update the issue with the actual code that is producing the error - and no images please!

**Comment by jeffgbutler** [comment]
I just noticed something else - it looks like you are generating code for Spring, but using a MyBatis mapper. That won't work.

Check the imports in this class - make sure you are using the MyBatis imports and not the Spring imports.

**Comment by wenlongwanggithub** [comment]
OMG, thanks for your reminder, the import of 'select' is wrong.

import org.mybatis.dynamic.sql.util.kotlin.mybatis3.select
import org.mybatis.dynamic.sql.util.kotlin.spring.select

And thanks for the amazing project again.

**Comment by jeffgbutler** [comment]
@wenlongwanggithub I'm glad it was an easy fix. Your usage for this complex select statement is really awesome!
