### ISSUE TITLE
How to get new record id

### ISSUE THREAD

**Issue by fanwmeng** [mybatis/mybatis-dynamic-sql#83]
when I use  insert method, how can I get the new record id?
for example:

```
Employee record = new Employee();
record.setFirstName("Joe");

InsertStatementProvider insertStatement = insert(record)
    .into(employee)
    .map(firstName).toProperty("firstName")
    .build()
    .render(RenderingStrategy.MYBATIS3);

int rows = mapper.insert(insertStatement);
```

The result of insert method is rows of inserted recored, but I want to get the id of the new record.

**Comment by jeffgbutler** [comment]
You need to configure the mapper to retrieve the new key. There's an example here:

https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/generated/always/mybatis/GeneratedAlwaysAnnotatedMapper.java#L49

**Comment by fanwmeng** [comment]
> You need to configure the mapper to retrieve the new key. There's an example here:
> 
> https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/generated/always/mybatis/GeneratedAlwaysAnnotatedMapper.java#L49

ok。This problem has resolved. thanks!

**Comment by libinglong** [comment]
> You need to configure the mapper to retrieve the new key. There's an example here:
> 
> https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/generated/always/mybatis/GeneratedAlwaysAnnotatedMapper.java#L49

the link is 404 now.

**Comment by jeffgbutler** [comment]
Here's a permalink to an example:

https://github.com/mybatis/mybatis-dynamic-sql/blob/759d8ecce2ff2d23fb40f54d9b96b40240198ba2/src/test/java/examples/generated/always/mybatis/GeneratedAlwaysMapper.java
