### ISSUE TITLE
Could it be a transaction bug in the mybatis dynamic SQL framework?

### ISSUE THREAD

**Issue by VertigoTY** [mybatis/mybatis-dynamic-sql#875]
The insertSelective method in mybatis dynamic SQL used to insert a table at the same time point on Alibaba Cloud has encountered an issue where only one piece of data was successfully inserted. The server's log records the ID of the data that was not inserted into the table, and the corresponding Alibaba Cloud MySQL (blog) database operation log does not record the data that was not inserted. Is this the reason why the framework transaction was not committed

**Comment by jeffgbutler** [comment]
I'm sorry, but I don't really understand the question. However, MyBatis Dynamic SQL only generates SQL, it does not execute that SQL. Also, MyBatis Dynamic SQL doesn't do any transaction processing.

We could try to help, but we will need more information. We will need to see some code and log entries. And please DO NOT use images of code!

**Comment by VertigoTY** [comment]
Sorry, I didn't describe it very clearly. We are currently facing a problem where we are inserting data into the same table at the same time and place. The operation in one interface and local logs are all successful, but there are a few SQL statements missing from the database. I don't know if it is due to concurrency or other issues caused by the framework, or if it is a problem with our code. In our project, this table already has more than 1.5 million data points, but currently only 5 data points are in this situation. I hope to receive some help.

**Comment by VertigoTY** [comment]
Firstly, we have two interfaces A (insert dba)/B (insert dbb), and the user calls both interfaces at the same time. After the logic of interface B is completed, there will be some subsequent joint operations to insert a piece of dba data. At this point, the request for interface A is successful in the local log, and there are some missing SQL statements from interface A in the database. However, the request for interface B to insert DBA data in subsequent joint operations is successful

**Comment by VertigoTY** [comment]
Sorry, could you please correct about 800 of them

**Comment by VertigoTY** [comment]
Okay, I've probably already troubled the problem, thank you for the answer.
