### ISSUE TITLE
It's not possible to have a group by clause directly after a where clause

### ISSUE THREAD

**Issue by tnicolas29200** [mybatis/mybatis-dynamic-sql#9]
Hello,

I encounter a problem with a simple query : i want to do 
SELECT field FROM table WHERE id = 1 GROUP BY field

so i write my query like this :
select(field).from(table).where(id, isEqualTo(1)).groupBy(field);

But after the where clause, there's no groupBy method.

In the QueryExpressionDSL class, the where clause return an QueryExpressionWhereBuilder which contain only "union", "orderBy" clause but not "groupBy", so i can't use a group by clause without having an order by or union clause before

**Comment by jeffgbutler** [comment]
Fixed via #14
