### ISSUE TITLE
Table name cannot be keywords of mysql.

### ISSUE THREAD

**Issue by luozhenyu** [mybatis/mybatis-dynamic-sql#93]
For example, I create a table named "order".

By default, mybatis dynamic sql will not escape the table name "order" and jdbc will report a error.
```
org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order (id, ' at line 1
##
```
If it is possible that mybatis dynamic sql escapes table name before execute queries.

My temporary solution is escaping table name in constructor of org.mybatis.dynamic.sql.SqlTable .
```
import org.mybatis.dynamic.sql.SqlTable;

class OrderSqlTable extends SqlTable {
    OrderSqlTable() {
        super("`order`");
    }
}
```

Perhaps, it is a feature? It allows developers to customize their SQL? Or better performance?
```
package org.mybatis.dynamic.sql.insert.render;
...
public class InsertRenderer<T> {
...
    private String calculateInsertStatement(FieldAndValueCollector<T> collector) {
        return "insert into" //$NON-NLS-1$
                + spaceBefore(model.table().name())
                + spaceBefore(collector.columnsPhrase())
                + spaceBefore(collector.valuesPhrase());
    }
```

**Comment by jeffgbutler** [comment]
I think that escaping the name yourself is the best option. Otherwise the library would need to do some runtime work to figure out if names needed to be escaped. And different databases have different escaping requirements. 

For example, MyBatis Generator will figure all that out during code generation and escape the names if needed.  Then it is not a run time issue.

**Comment by luozhenyu** [comment]
Thanks for your advice. It makes sense.
