### ISSUE TITLE
support for self-join 

### ISSUE THREAD

**Issue by peacetrue** [mybatis/mybatis-dynamic-sql#95]
when i use :
`SqlBuilder.select(...)
                .from(table, "a")
                .join(table, "b")
`
the result is :
`select ... from table b join table b on b.id = b.id`

**Comment by jeffgbutler** [comment]
This should have been fixed with #55. What version are you using?

**Comment by jeffgbutler** [comment]
There was a fix for this, but it is more involved than you might think. You will need to define two SQLTable objects and associated columns. At the moment, it won't work the way you have it. I'm not sure there is a good fix for that, but I will think about it.

**Comment by peacetrue** [comment]
I have see the ``JoinMapperTest``, it is ok.

**Comment by carzyhub** [comment]
How do I use self Join in Kotlin
